const datos_ESP ={
    Género:"Género",
    Especie:"Especie",
    Subespecie:"Subespecie",
    FormaDeVida:"Formas de vida",
    Material:"Material",
    Altura:"Altura",
    Constitucion:"Constitución",
    Pechos:"Tamaño de pechos",
    Culo:"Tamaño de culo",
    Muslos:"Tamaño de muslos y cadera",
    Genitales:"Genitales y tamaño",
    Testículos:"Tamaño de testículos",
    ModificacionesCorporales:"Modificaciones corporales",
    LugarDeNacimiento:"Lugar de nacimiento",
    LugarDeResidencia:"Lugar de residencia",
    Faccion:"Facción",
    Masculinotitle:"Masculino",
    Masculinodesc:"Eres un ser masculino",
    Femeninotitle:"Femenino",
    Femeninodesc:"Eres un ser femenino",
    "No-Binarietitle":"No Binarie",
    "No-Binariedesc":"Eres un ser no binarie",
    Humanotitle:"Humano",
    Humanodesc:"Eres un humano. Objetivamente, la peor decisión, pero a cambio tienes más puntos para gastar en otras secciones.",
    Plasmoidetitle:"Plasmoide",
    Plasmoidedesc:"Eres un Plasmoide. Tu especie tiene el esqueleto segmentado, y por complejos sistemas físicos, puedes cambiar tu forma y estructura corporal general",
    Transmutadotitle:"Transmutado",
    Transmutadodesc:"Eres un Transmutado. No tienes estructura, eres un montón de tu material que puede tomar diversas formas.",
    "No-Carbonoidetitle":"No Carbonoide",
    "No-Carbonoidedesc":"Eres un No Carbonoide. Tienes estructura interna similar en muchos casos a la plasmoide, pero adaptada al material del que estás hecho, aprovechando sus capacidades.",
}