const datos_ENG ={
    Género:"Gender",
    Especie:"Species",
    Subespecie:"Subespecies",
    FormaDeVida:"Lifeforms",
    Material:"Material",
    Altura:"Height",
    Constitucion:"Constitution",
    Pechos:"Chest size",
    Culo:"Ass size",
    Muslos:"Hips and thighs size",
    Genitales:"Genitals",
    Testículos:"Testicles size",
    ModificacionesCorporales:"Body modifications",
    LugarDeNacimiento:"Place of birth",
    LugarDeResidencia:"Place of residence",
    Faccion:"Faction",
    Masculinotitle:"Masculine",
    Masculinodesc:"You're a masculine being",
    Femeninotitle:"Feminine",
    Femeninodesc:"You're a feminine being",
    "No-Binarietitle":"Non binary",
    "No-Binariedesc":"You're a non binary being",
 Humanotitle:"Human",
    Humanodesc:"You're a human. It's objectively the worst decision, but, hey, you have more points to spend!",
    Plasmoidetitle:"Plasmoid",
    Plasmoidedesc:"You're a Plasmoid. Your species has a segmented skeleton and, thanks to some complex physical systems, you can change your shape and general body structure",
    Transmutadotitle:"Transmuted",
    Transmutadodesc:"You're a Transmuted. You don't have any structure, as you're just a mass of your material that can take any shape or form",
    "No-Carbonoidetitle":"Non Carbonoid",
    "No-Carbonoidedesc":"You're a Non Carbonoid. You have internal structure, just like a plasmoid has, but adapted to your own material, so you get the most out of it.",
    PT1title:"Type 1 Plasmoid",
    PT1desc:"Known for their elastic and malleable body at room temperature, they're the most \"solid\" option out of the three",
    PT2title:"Type 2 Plasmoid",
    PT2desc:"Known for their viscous and gelatinous body at room temperature, you may leave some residue wherever you go",
    PT3title:"Type 3 Plasmoid",
    PT3desc:"Known for their fluid and liquid body at room temperaature, you'll have to be a bit careful not to go down the drains",
    PT0title:"Type 0 Plasmoid",
    PT0desc:"A very rare variant, able to modify their state at will",
    TT1title:"Type 1 Transmuted",
    TT1desc:"Transmuted made from pure elements, simple compounds and metals, from gold up to some explosives",
    TT2title:"Type 2 Transmuted",
    TT2desc:"Transmuted made from organic compounds, in case you've ever wanted to be a protein, or made from alcohol",
    TT3title:"Type 3 Transmuted",
    TT3desc:"Food-based Transmuted. They almost have the most variety, you have everything!",
    NCT1title:"Type 1 Non-Carbonoid",
    NCT1desc:"Non-Carbonoids made from pure elements, simple compounds and metals. Now being made of silver won't trouble you",
    NCT2title:"Type 2 Non-Carbonoid",
    NCT2desc:" Non-Carbonoid made from organic compounds. You're a walking generator of your own material, and maybe of some others",
    NCT3title:"Type 3 Non-Carbonoid",
    NCT3desc:"Food-based Non-Carbonoids. Can't crave your favorite food if you're made out of it!",
    alturaEnanatitle:"Tiny",
    alturaEnanadesc:"You're going to be at most like half a meter tall. Beware the rats!",
    alturaPequeñatitle:"Small",
    alturaPequeñadesc:"With a bit of luck, you'll reach a meter of height. Get prepared to have to get on people's shoulders to see stuff",
    alturaBajatitle:"Short",
    alturaBajadesc:"You're between a meter and a meter and a half. Now you can sit on the table with no trouble",
    alturaMediatitle:"Medium",
    alturaMediadesc:"Now you're in a more common range, between 1,60m and 1,90m. You'll be able to talk to people face-to-face",
    alturaAltatitle:"Tall",
    alturaAltadesc:"Here, we reach 2,20m. You'll stand out in any room you're in",
    alturaEnormetitle:"Huge",
    alturaEnormedesc:"If two meters felt short to you, now you'll reach the three meter mark! But be careful with the doors, alright?",
    alturaGigantetitle:"Gigantic",
    alturaGigantedesc:"Five meters? It's a relief you can control your body, because it would be difficult finding a place to live otherwise",
    constDelgadatitle:"Thin",
    constDelgadadesc:"You don't have excessive muscle nor fat on your bones. Is it a new diet?",
    constIntermediatitle:"Intermediate",
    constIntermediadesc:"Pretty autodescriptive, you'll be in the human average, not too thin, not too bulky",
    constEnFormatitle:"Fit",
    constEnFormadesc:"You have a nice ammount of muscle, and their shape can be seen under the skin",
    constMusculadatitle:"Toned",
    constMusculadadesc:"Your muscles are almost at skin level, with some impressive definition. With those biceps you could lift the Hegemony's economy",
    constCorpulentatitle:"Hefty",
    constCorpulentadesc:"Big boned, huggable, plump. There are a thousand adjetives, but you have a nice dad (or mom) bod",
    constEsfericatitle:"Spherical",
    constEsfericadesc:"Right now, you are a balloon. Maybe you've been stabbed with an inflator, or may have inhaled too strongly, but you'll be bouncing around",
    planatitle:"Flat chest",
    planadesc:"Flat, flat as a plank... An advantage, if you don't want back pain, or if you don't want two fat balls on your chest. To each their own",
    pocoPechotitle:"Small chest",
    pocoPechodesc:"You have some chest. Even though many people would consider it little, it is the most practical size for athletics and jumping around",
    intermediotitle:"Intermediate",
    intermediodesc:"El punto medio perfecto, suficientemente grandes como para que se noten, pero no lo suficiente como para que molesten. Pero, ¿De verdad estamos pensando en practicidad?",
    grandetitle:"Grandes",
    grandedesc:"Now we're talking! Good, big, and beautiful, perfect for grabbing and showing off. Suitable for a true mammarie glands' fan!",
    enormestitle:"Enormous",
    enormesdesc:"Alright, some people would say you've gone too far, but I'm not some people! They are as big as, or bigger than, your head. Pretty, soft and squishy! Perfect for sleeping on them!",
    dignasDeUnaSantatitle:"Worthy of a Saint",
    dignasDeUnaSantadesc:"Perfection for some people, jealusy for others, pure craziness for some others. You have some BIG boobs, so much so that they may be closer to pillows than part of your body. But, hey, if you let me touch 'em...",
    SANTASTETASDELAMADREtitle:"MOTHER'S HOLY RUBBERY TITS",
    SANTASTETASDELAMADREdesc:"Gigantic, enormous, IMMEASURABLE. Now they really are two giant pillows attached to your body. Difficult to lift and carry. But I would love to sleep on them...",
    planotitle:"Buttless",
    planodesc:"I don't know how you've done this, but you don't have a butt. Your buttocks are barely inexistent. Your thighs connect directly with your hips. It's not even a flat ass, it's... Are you alright?",
    culoCarpetatitle:"Flat ass",
    culoCarpetadesc:"Well, you have little ass, but you have something. You don't stand out, nobody will look at you while outside, not even if you want to, but you at least have some NATURAL proportions.",
    culitotitle:"Small ass",
    culitodesc:"A nice little ass, and relatively well formed. It's not very notable, let's say, but it's comfortable and big enough to be called pretty... for a human.",
    buenCulotitle:"Nice ass",
    buenCulodesc:"Look, now I would accept having dinner with you. You have a nice ass, very well formed, nice size, and ready to be grabbed and spanked. Send your exercise routine and diet, c'mon",
    culazotitle:"Big ass",
    culazodesc:"Tremendous ass! Big, toned, soft and strong. Normal people will envy you. There is very little to say apart from that, TREMENDOUS ASS.",
    culoPerfectotitle:"Absolute buttal perfection",
    culoPerfectodesc:"Even more than a perfectt butt. The perfect mix of musculature and fat which results in an ass that will make any being envy you. Enormous, but not very impractical. And all chairs will be sofas for you. Lucky you!",
    asientoPortatiltitle:"Portable seat",
    asientoPortatildesc:"You don't even have an ass anymore, you have a beanie bag, you know, those balls you put on the floor and can even lay on them. SO big you can even sit standing up, but moving around must be a pain in the ass...",
    
    muslosPalillotitle:"Palillos",
    muslosPalillodesc:"Ya no es simplemente que siempre te saltes el día de pierna, sino que parece que llevas sin andar meses o años. ¿Puedes andar sin que se te partan las piernas? Habrá que probarlo...",
    muslosPlanostitle:"Planos",
    muslosPlanosdesc:"Sólo te saltas el día de piernas, normal, también te digo, es un puto coñazo... Aún así, no tienes nada que agarrar, de una forma humanamente posible, claro. Haz más ejercicio, por favor.",
    muslosIntermediostitle:"Decentes",
    muslosIntermediosdesc:"Unos muslos y caderas bastante decentillos, nada del otro mundo, pero nada desdeñables. Muy promedio, muy normal, muy... aburrido",
    muslosConCurvastitle:"Buenas Curvas",
    muslosConCurvasdesc:"¡Se notan los meses de gimnasio! O la buena genética, cualquiera de las dos. Tienes buenos muslos y caderas, bastante gente te envidiaría, la verdad",
    muslosChildBearingtitle:"Muslos para repoblar un pueblo moribundo",
    muslosChildBearingdesc:"La envidia de todo el mundo. Tienes unos muslos y unas caderas fuertes, poderosos y con la cantidad justa y necesaria de grasa. Perfección absoluta. ¿Cuándo me vas a reventar a golpes de cadera?",
    muslosFuertestitle:"Parte melones",
    muslosFuertesdesc:"Joder... Por favor, aplástame con esos muslos capaces de partir melones. Apriétame la cabeza hasta que reviente y acabe desparramada por las paredes, por favor...¿De qué estábamos hablando?",
    muslosBloqueaPuertastitle:"Bloquea puertas",
    muslosBloqueaPuertasdesc:"¿Te acuerdas de lo que decía de que lo excesivo era para cobardes? Bueno, te lo has tomado a muslos, por lo que veo. Tienes muslos y caderas tan grandes como alta es una persona. No creo que puedas pasar por ninguna puerta sin reventarla. Pero como se diría en mi pueblo: Si no entra, que raje",
    genitalesVaginatitle:"Vagina",
    genitalesVaginadesc:"Felicidades, ahora tienes lo que la mayor parte de gente del planeta elige tener. ¡Pero sin problema, que a casi todo el mundo le gusta!",
    genitalesClitoristitle:"Clítoris",
    genitalesClitorisdesc:"Una adición razonable en todos los casos, algo tienes que tener para entretenerte en tus ratos libres, ¿eh?",
    genitalesPeneClitoristitle:"Pene clítoris",
    genitalesPeneClitorisdesc:"...no voy a juzgar esto, si te van estas cosas, ¿pero para eso eliges tener pene?",
    genitalesMicropenetitle:"Micropene",
    genitalesMicropenedesc:"Bueno, este por lo menos es más o menos usable. Quizás no te sirva mucho, pero se pueden hacer cosas con él",
    genitalesPenePequeñotitle:"Pene pequeño",
    genitalesPenePequeñodesc:"No entras ya en que tu condición tenga nombre, pero aún así... Míralo por el lado bueno, no se te marcará por debajo de la ropa (si llevas)",
    genitalesPeneMedianotitle:"Pene mediano",
    genitalesPeneMedianodesc:"Hay quien dice que la virtud está en la moderación, ni muy grande ni muy pequeño, justo en el punto",
    genitalesPeneGrandetitle:"Pene grande",
    genitalesPeneGrandedesc:"Aquí ya estamos empezando a hablar. La mayoría de juguetes vienen de este tamaño, así que no te hará competencia un trozo de plástico",
    genitalesPeneEnormetitle:"Pene enorme",
    genitalesPeneEnormedesc:"Con esta arma, podrían detenerte. ¡No tendrás que preocuparte de no saber con qué abrir nueces!",
    genitalesBlostetitle:"El Bloste",
    genitalesBlostedesc:"Y ahora preguntarás, ¿qué es el Bloste? Pues la verdad es que no lo sé. ¿Por qué no le das y lo compruebas?",
    testOvariostitle:"Ovarios",
    testOvariosdesc:"La opción correcta si quieres ser capaz de engendrar descendencia por tu propia cuenta, como yo.",
    testInexistentestitle:"Inexistentes",
    testInexistentesdesc:"A fin de cuentas, ¿quién querría tener una debilidad tan abierta?",
    testInternostitle:"Internos",
    testInternosdesc:"Buena opción, si aún quieres, y te facilita la producción de gametos",
    testPequeñostitle:"Pequeños",
    testPequeñosdesc:"A ver, no puedo decir nada, ¿pero has estado abusando de la testosterona de la Hegemonía?",
    testMedianostitle:"Medianos",
    testMedianosdesc:"Un tamaño adecuado. No quedarán demasiado fuera de lugar a menos que haya una diferencia de tamaño importante con el pene",
    testGrandestitle:"Grandes",
    testGrandesdesc:"Buenas bolas, buen tamaño, buena consistencia... Aunque un poco grandes para mi gusto",
    testEnormestitle:"Enormes",
    testEnormesdesc:"Joder, con unos de ese tamaño, estoy bastante segura de que podrías ahogar a alguien",
    MusculosReforzadostitle:"Músculos reforzados",
    MusculosReforzadosdesc:"Debido a un entrenamiento de alta intensidad o una modificación al maleabilizarte, tus capacidades físicas ahora están por las nubes",
    MejorSistemaNerviosotitle:"Sistema nervioso optimizado",
    MejorSistemaNerviosodesc:"Quizás has hecho muchos sudokus o te has hecho con órganos de la doctora Tiff, pero ahora tu memoria, atención, y procesamiento se han disparado",
    ControlCorporalAvanzadotitle:"Control corporal avanzado",
    ControlCorporalAvanzadodesc:"Es cierto que la gente maleable puede hacer casi lo que quiera con su cuerpo, ¡pero con esto te será más natural y fácil!",
    lnHegemoniatitle:"La Hegemonía",
    lnHegemoniadesc:"El último baluarte de la humanidad... es un sitio decadente lleno de odio y miseria. Siempre bajo la atenta mirada del Gran Hegemón y dispuestos a defenderse con uñas y dientes de lo que, según la propaganda, son horrorosos monstruos comehumanos (Joder, ya sé que no damos muy buena imagen, pero tan malos no somos, ¿No?)",
    lnLibertastitle:"Libertas",
    lnLibertasdesc:"El centro de toda la actividad del mundo, una ciudad cosmopolita que reune a gente de todos lados ya no del mundo, ¡Sino del universo! Es conocida por sus universidades, laboratorios destinados a la investigación de formas de vida maleables y por acoger a cualquier persona que quiera estar ahí por libre decisión. (Yo vivo y trabajo allí, por cierto, ¡Saludos desde Libertas!)",
    lnLechoDeSantatitle:"Lecho de la Santa",
    lnLechoDeSantadesc:"(DISCLAIMER: LEGALMENTE NO PUEDO SER IMPARCIAL) Actual (Y única a lo largo de la historia) sede de la Congregación de las Hermanas de Santa Megumi. El Lecho es altamente conocido por lo peculiar de su fauna y flora basadas en tentáculos y serpientes, además de porque todos los edificios están conectados por barras, grietas y ganchos para que las plasmoides tipo 1 puedan saltar, balancearse y rebotar. ¡También es el centro médico en el que se reúnen las mayores eminencias en cualquier tipo de disciplina! (Y si quieres tener la noche de tu vida, créeme, este es tu sitio)",
    lnPalasextitle:"El Palasex",
    lnPalasexdesc:"A ver, técnicamente no es un país per se, pero sí que es una zona políticamente independiente... Bueno, este sitio es básicamente un mega parque de atracciones en el que LITERALMENTE te puedes encontrar de todo, desde cangrejoides de más allá de La Llama buscando nuevos vínculos hasta fanáticos de un tipo muy específico de terror de Edén de hace milenios, ¡Y todos ellos con su zona delimitada!",
    lnElFervortitle:"El Fervor",
    lnElFervordesc:"El país con la historia, cultura y todo en general, más longevo de este mundo (Coño y tanto, como que lleva 3000000 años existiendo, no te jode). Principalmente poblado por plasmoides tipo 3, por lo que mucha de la arquitectura está basada en tuberías, canales y ríos por los que alguien líquido puede simplemente fluir (Algún día tendría que probarlo...). Ah, y es la zona con más conocimiento arcano y espiritista del mundo. ¡Todo el mundo es un elementalista!",
    lnBiuTauOrtitle:"BiuTau Oriental",
    lnBiuTauOrdesc:"Una zona marcada por el conflicto con sus vecinos occidentales (En realidad sólo se han peleado un par de veces por un río medio congelado, así que...). Irrigado por el río BiuTau y cubierto de pantanos y junglas de plantas y seres gelatinosos, este es el sitio ideal para una plasmoide tipo 2. ¡Ten cuidado y no te estampes con los árboles!",
    lnBiuTauOcctitle:"BiuTau Occidental",
    lnBiuTauOccdesc:"Una zona marcada por el conflicto con sus vecinos orientales (Estos son los que suelen atacar más, por cierto, por eso el río está medio congelado...). Irrigado por el río BiuTau y cubierto por una frondosa selva congelada hasta arriba de nievorilas, ranárboles de chocolate y demás flora y fauna helada, por lo que es el asentamiento perfecto para las transmutadas y no carbonoides de materiales congelados (O si te gusta el helado, claro).",
    lnArchipielagotitle:"Archipiélago de los Santos",
    lnArchipielagodesc:"Curiosamente, no hay mucha gente que haya visitado este pequeño archipiélago gobernado por los Santos Zoo'Mani. Lo único que sabemos es que tienen una cultura basada en los 'deportes de contacto', lo que normalmente se reduce a una glorificación de la violencia en busca de la emoción de la confrontación... ¡Pero eh, su gente es majísima si no te dejas intimidar por sus formas medio animales!  ",
    lnEnclavestitle:"Enclaves Libres",
    lnEnclavesdesc:"Un conjunto de pequeños estados federales llamados distritos, cada uno de ellos dedicado a la manufactura y el comercio de un tipo de mercancía distinto. Este país gobernado por El Don de los Enclaves se fundó como un refugio para la gente que escapó de la Hegemonía durante la rebelión fallida y de las fábricas de Hall&Co. Se come de puta madre y se vive mejor, honestamente, ¡Por algo es la segunda zona más variada del mundo!",
    lnGranEmporiotitle:"Gran Emporio de Hall",
    lnGranEmporiodesc:"Lo siento, de verdad que lo siento... Si has nacido aquí, huye, si vives aquí, huye. Da igual lo que seas, si estás aquí mucho tiempo, serás poco más que una máquina expendedora más que ordeñar. No se puede decir que este sitio tenga población, sino eso, recursos humanos que serán explotados por el chocolateado puño de Hellen Hall.",
    lnOasistitle:"El Oasis",
    lnOasisdesc:"¡Mira, un buen sitio para vivir! Fundado por la Doctora Tiffanny y las supervivientes de las fábricas de Hall&Co, este es un auténtico remanso de paz para las no carbonoides tipo 3, lleno de fauna y flora dulce y abundante para asegurar su autonomía. ¡El sitio perfecto para unas vacaciones y para cagarte en los muertos de la gente que te ha esclavizado!",
    lnTimarAurhumtitle:"Timar Aurhum",
    lnTimarAurhumdesc:"El país con mayor poder militar del oeste, fundado por el Gran Rey Aureliano tras la rebelión fallida en las cuevas occidentales influenciadas por el núcleo de la protección y el metal. Actualmente es una monarquía absolutista en la que poco puedes hacer si quieres algo de privacidad, ¡Pero eh, puedes ver arañas de cristal y dragones de metal gigantes con cuatro puños (Están guapísimos los Geidures, ¿A que sí?)!",
    lrHegemoniatitle:"La Hegemonía",
    lrHegemoniadesc:"El último baluarte de la humanidad... es un sitio decadente lleno de odio y miseria. Siempre bajo la atenta mirada del Gran Hegemón y dispuestos a defenderse con uñas y dientes de lo que, según la propaganda, son horrorosos monstruos comehumanos (Joder, ya sé que no damos muy buena imagen, pero tan malos no somos, ¿No?)",
    lrLibertastitle:"Libertas",
    lrLibertasdesc:"El centro de toda la actividad del mundo, una ciudad cosmopolita que reune a gente de todos lados ya no del mundo, ¡Sino del universo! Es conocida por sus universidades, laboratorios destinados a la investigación de formas de vida maleables y por acoger a cualquier persona que quiera estar ahí por libre decisión. (Yo vivo y trabajo allí, por cierto, ¡Saludos desde Libertas!)",
    lrLechoDeSantatitle:"Lecho de la Santa",
    lrLechoDeSantadesc:"(DISCLAIMER: LEGALMENTE NO PUEDO SER IMPARCIAL) Actual (Y única a lo largo de la historia) sede de la Congregación de las Hermanas de Santa Megumi. El Lecho es altamente conocido por lo peculiar de su fauna y flora basadas en tentáculos y serpientes, además de porque todos los edificios están conectados por barras, grietas y ganchos para que las plasmoides tipo 1 puedan saltar, balancearse y rebotar. ¡También es el centro médico en el que se reúnen las mayores eminencias en cualquier tipo de disciplina! (Y si quieres tener la noche de tu vida, créeme, este es tu sitio)",
    lrPalasextitle:"El Palasex",
    lrPalasexdesc:"A ver, técnicamente no es un país per se, pero sí que es una zona políticamente independiente... Bueno, este sitio es básicamente un mega parque de atracciones en el que LITERALMENTE te puedes encontrar de todo, desde cangrejoides de más allá de La Llama buscando nuevos vínculos hasta fanáticos de un tipo muy específico de terror de Edén de hace milenios, ¡Y todos ellos con su zona delimitada!",
    lrElFervortitle:"El Fervor",
    lrElFervordesc:"El país con la historia, cultura y todo en general, más longevo de este mundo (Coño y tanto, como que lleva 3000000 años existiendo, no te jode). Principalmente poblado por plasmoides tipo 3, por lo que mucha de la arquitectura está basada en tuberías, canales y ríos por los que alguien líquido puede simplemente fluir (Algún día tendría que probarlo...). Ah, y es la zona con más conocimiento arcano y espiritista del mundo. ¡Todo el mundo es un elementalista!",
    lrBiuTauOrtitle:"BiuTau Oriental",
    lrBiuTauOrdesc:"Una zona marcada por el conflicto con sus vecinos occidentales (En realidad sólo se han peleado un par de veces por un río medio congelado, así que...). Irrigado por el río BiuTau y cubierto de pantanos y junglas de plantas y seres gelatinosos, este es el sitio ideal para una plasmoide tipo 2. ¡Ten cuidado y no te estampes con los árboles!",
    lrBiuTauOcctitle:"BiuTau Occidental",
    lrBiuTauOccdesc:"Una zona marcada por el conflicto con sus vecinos orientales (Estos son los que suelen atacar más, por cierto, por eso el río está medio congelado...). Irrigado por el río BiuTau y cubierto por una frondosa selva congelada hasta arriba de nievorilas, ranárboles de chocolate y demás flora y fauna helada, por lo que es el asentamiento perfecto para las transmutadas y no carbonoides de materiales congelados (O si te gusta el helado, claro).",
    lrArchipielagotitle:"Archipiélago de los Santos",
    lrArchipielagodesc:"Curiosamente, no hay mucha gente que haya visitado este pequeño archipiélago gobernado por los Santos Zoo'Mani. Lo único que sabemos es que tienen una cultura basada en los 'deportes de contacto', lo que normalmente se reduce a una glorificación de la violencia en busca de la emoción de la confrontación... ¡Pero eh, su gente es majísima si no te dejas intimidar por sus formas medio animales!  ",
    lrEnclavestitle:"Enclaves Libres",
    lrEnclavesdesc:"Un conjunto de pequeños estados federales llamados distritos, cada uno de ellos dedicado a la manufactura y el comercio de un tipo de mercancía distinto. Este país gobernado por El Don de los Enclaves se fundó como un refugio para la gente que escapó de la Hegemonía durante la rebelión fallida y de las fábricas de Hall&Co. Se come de puta madre y se vive mejor, honestamente, ¡Por algo es la segunda zona más variada del mundo!",
    lrGranEmporiotitle:"Gran Emporio de Hall",
    lrGranEmporiodesc:"Lo siento, de verdad que lo siento... Si has nacido aquí, huye, si vives aquí, huye. Da igual lo que seas, si estás aquí mucho tiempo, serás poco más que una máquina expendedora más que ordeñar. No se puede decir que este sitio tenga población, sino eso, recursos humanos que serán explotados por el chocolateado puño de Hellen Hall.",
    lrOasistitle:"El Oasis",
    lrOasisdesc:"¡Mira, un buen sitio para vivir! Fundado por la Doctora Tiffanny y las supervivientes de las fábricas de Hall&Co, este es un auténtico remanso de paz para las no carbonoides tipo 3, lleno de fauna y flora dulce y abundante para asegurar su autonomía. ¡El sitio perfecto para unas vacaciones y para cagarte en los muertos de la gente que te ha esclavizado!",
    lrTimarAurhumtitle:"Timar Aurhum",
    lrTimarAurhumdesc:"El país con mayor poder militar del oeste, fundado por el Gran Rey Aureliano tras la rebelión fallida en las cuevas occidentales influenciadas por el núcleo de la protección y el metal. Actualmente es una monarquía absolutista en la que poco puedes hacer si quieres algo de privacidad, ¡Pero eh, puedes ver arañas de cristal y dragones de metal gigantes con cuatro puños (Están guapísimos los Geidures, ¿A que sí?)!",
    faccHegemoniatitle:"Hegemonía de todos los Hombres",
    faccHegemoniadesc:"Vale, de verdad, no sé qué coño haces usando esto. ¿Qué? ¿Tu amo Smith te ha soltado de la correa y te ha permitido meterte en la red de fuera del país? Bueno, si es así... Ya sabes lo que hay, un grupo de fanáticos extremistas que odian cualquier cosa que no sea humana. ¿Qué eres, un currito más bajo la opresión del Hegemón, un inspector, UNA LUZ DE GAS...? O igual quieres cambiar las cosas desde dentro...",
    faccLaboratoriostitle:"Laboratorios Riuter",
    faccLaboratoriosdesc:"Sé que ya he dicho que no puedo ser imparcial, pero, joder, es que trabajo allí... Los Laboratorios Riuter son el centro más prestigioso (El único) de investigación de formas de vida maleables en todo Aelfatum. Presididos por la Doctora Yulva Maltarum (LA JEFA), el Doctor Anthony Gums (DON JEFE) y, últimamente, la Doctora Camelia Thomson. Pues eso, que es un sitio en el que trabajamos para descubrir los secretos de lo maleable. ¡Únete a nosotras, estira tus límites (El eslogan cursi también era obligatorio)!",
    faccHermanastitle:"Congregación de las Hermanas de Santa Megumi de la Vida y Su Elástica Faz",
    faccHermanasdesc:"La otra facción de una servidora y la que literalmente me salvó la vida. Son un conjunto de pequeños conventos, cada uno presidido por una santa distinta, desde Katarina hasta Ophelia. Aún así, esta congregación centrada en el servicio a las demás, la medicina, la sanación y aumentar la población y el placer en el mundo, hoy en día está 'gobernada' por la Gran Santa Megumi de la Vida y gobernada por su madre, Santa Alicia del Vacío. Si quieres echar un buen polvo, ayudar a la gente y encima que te ayuden, ¡Este es tu sitio! ",
    faccFervortitle:"Elementalistas del Fervor",
    faccFervordesc:"¡Las mayores expertas en espiritismo y ciencia intrasencial del planeta! ¿Qué coño del planeta? DE LA GALAXIA. Hace mucho tiempo eran cinco países distintos, pero todos se acabaron uniendo en una única facción tras la Ascensión de Sanabaur. En resumen, mucha Intra, muchos elementos y mucho vino, ¡Todo ello bajo la atenta mirada de La Tejedestinos en persona (Atenta siempre que no esté como una puta cuba, claro)!",
    faccAprendizastitle:"Aprendizas de Azxqerfo",
    faccAprendizasdesc:"¿Te gustan las artes marciales, las enfermedades y los árboles? ¿Quieres aprender las bondades de meterte un clavo por el culo? ¿Te apetecería probar suerte con LA PIEDRA MÁGICA DEL CONTROL? ¡Pues pídele cita al Doctor Azxqerfo y deja que te entrene junto a eminencias de la lucha como Bea, Bea y... BEA! De aquí sale la gran mayoría del personal médico del sur del planeta, eso sí, te advierto que su definición de curar es... poco ortodoxa",
    faccOasistitle:"Supervivientes del Oasis",
    faccOasisdesc:"Ufff, esta es dura, por lo que veo. Todas las personas de esta facción son esclavas fugadas de las fábricas de Hall que han podido fundar su propio país en el BiuTau Occidental. Es una facción basada en la cooperación, la libertad y el amor por una vida individual justa. Y parece que todo va perfectamente, bueno, todo lo bien que puede irle a un estado recién formado. Pero Tiff hace lo que puede (Por las gomosas tetas de La Madre, qué orgullosas estamos de ella).",
    faccHallYCotitle:"Hall &Co: Foods And Experiences",
    faccHallYCodesc:"¿Seguís existiendo hoy en día? Pensaba que después de lo que le pasó a vuestra je... Ehem. Hall&Co, Hall&Co... La empresa que monopolizó la producción de cualquier producto que podría extraerse de una maleable... Mediante la esclavitud de personas a las que ordeñaba como si fueran básicamente bhures o frutas. Si te gusta el dinero, la esclavitud y la explotación (Además de reducir y torturar tanto a las personas que literalmente dejan de considerarse personas a sí mismas), esta es tú facción, supongo...",
    faccEnclavestitle:"Enclaves Libres",
    faccEnclavesdesc:"La facción más hetereogénea y variada de todas. Dividida en capitanías que funcionan como una máquina perfectamente engrasada bajo la atenta mirada y apoyo del Don de los Enclaves. ¿Quieres cocinar? ¡Ve al distrito de la restauración! ¿Quieres producir químicos? ¡PhlecksChem te recibirá con los brazos abiertos! ¿Quieres un par de tragos? ¡El Bubble's siempre está abierto y Gums siempre estará ahí para ti! Eso sí, recuerda pagar tus impuestos y responder a los llamados de auxilio de la gente a tu alrededor, o podría ser que nadie responda a los tuyos.",
    faccTimarAurhumtitle:"Ejército Dorado de Timar Aurhum",
    faccTimarAurhumdesc:"¡Honrada, fuerte, poderosa y profesional! Así es como se define a sí misma la gente de Timar Aurhum (Se suelen olvidar de la parte del palo metido por el culo, pero bueno). Este orgulloso pueblo de soldados, herreros y mineros está hoy en día dividido por un conflicto de sucesión. La gente tiene que decidir si apoyar al Rey Aureliano, fundador del país y gobernante absoluto expansionista del mismo, o a su hija, la Princesa Electra, que aboga por afrontar las relaciones exteriores con un enfoque más diplomático, por decirlo de alguna forma. ¿Qué eligirías tú?"
}
