const datos_ENG ={
    Género:"Gender",
    Especie:"Species",
    Subespecie:"Subespecies",
    FormaDeVida:"Lifeforms",
    Material:"Material",
    Altura:"Height",
    Constitucion:"Constitution",
    Pechos:"Chest size",
    Culo:"Ass size",
    Muslos:"Hips and thighs size",
    Genitales:"Genitals",
    Testículos:"Testicles size",
    ModificacionesCorporales:"Body modifications",
    LugarDeNacimiento:"Place of birth",
    LugarDeResidencia:"Place of residence",
    Faccion:"Faction",
    Masculinotitle:"Masculine",
    Masculinodesc:"You're a masculine being",
    Femeninotitle:"Feminine",
    Femeninodesc:"You're a feminine being",
    "No-Binarietitle":"Non binary",
    "No-Binariedesc":"You're a non binary being",
 Humanotitle:"Human",
    Humanodesc:"You're a human. It's objectively the worst decision, but, hey, you have more points to spend!",
    Plasmoidetitle:"Plasmoid",
    Plasmoidedesc:"You're a Plasmoid. Your species has a segmented skeleton and, thanks to some complex physical systems, you can change your shape and general body structure",
    Transmutadotitle:"Transmuted",
    Transmutadodesc:"You're a Transmuted. You don't have any structure, as you're just a mass of your material that can take any shape or form",
    "No-Carbonoidetitle":"Non Carbonoid",
    "No-Carbonoidedesc":"You're a Non Carbonoid. You have internal structure, just like a plasmoid has, but adapted to your own material, so you get the most out of it."
}