const datos_ESP ={
    Género:"Género",
    Especie:"Especie",
    Subespecie:"Subespecie",
    FormaDeVida:"Formas de vida",
    Material:"Material",
    Altura:"Altura",
    Constitucion:"Constitución",
    Pechos:"Tamaño de pechos",
    Culo:"Tamaño de culo",
    Muslos:"Tamaño de muslos y cadera",
    Genitales:"Genitales y tamaño",
    Testículos:"Tamaño de testículos",
    ModificacionesCorporales:"Modificaciones corporales",
    LugarDeNacimiento:"Lugar de nacimiento",
    LugarDeResidencia:"Lugar de residencia",
    Faccion:"Facción",
    Masculinotitle:"Masculino",
    Masculinodesc:"Eres un ser masculino",
    Femeninotitle:"Femenino",
    Femeninodesc:"Eres un ser femenino",
    "No-Binarietitle":"No Binarie",
    "No-Binariedesc":"Eres un ser no binarie",
    Humanotitle:"Humano",
    Humanodesc:"Eres un humano. Objetivamente, la peor decisión, pero a cambio tienes más puntos para gastar en otras secciones.",
    Plasmoidetitle:"Plasmoide",
    Plasmoidedesc:"Eres un Plasmoide. Tu especie tiene el esqueleto segmentado, y por complejos sistemas físicos, puedes cambiar tu forma y estructura corporal general",
    Transmutadotitle:"Transmutado",
    Transmutadodesc:"Eres un Transmutado. No tienes estructura, eres un montón de tu material que puede tomar diversas formas.",
    "No-Carbonoidetitle":"No Carbonoide",
    "No-Carbonoidedesc":"Eres un No Carbonoide. Tienes estructura interna similar en muchos casos a la plasmoide, pero adaptada al material del que estás hecho, aprovechando sus capacidades.",
    
    PT1title:"Plasmoide Tipo 1",
    PT1desc:"Conocidos por su cuerpo elástico y maleable a temperatura ambiente, son la elección más \"sólida\" de las tres.",
    PT2title:"Plasmoide Tipo 2",
    PT2desc:"Conocidos por su cuerpo viscoso y gelatinoso a temperatura ambiente, quizás manches un poco por donde pases.",
    PT3title:"Plasmoide Tipo 3",
    PT3desc:"Conocidos por su cuerpo líquido y fluido a temperatura ambiente, tendrás que tener un poco de cuidado para no irte por los desagües.",
    PT0title:"Plasmoide Tipo 0",
    PT0desc:"Variante rarísima y capaz de modificar su estado físico a voluntad.",
    TT1title:"Transmutado Tipo 1",
    TT1desc:"Transmutados de elementos puros, compuestos sencillos y metales, desde oro hasta ciertos explosivos.",
    TT2title:"Transmutado Tipo 2",
    TT2desc:"Transmutados de compuestos orgánicos, por si alguna vez has querido ser una proteína o de alcoholes.",
    TT3title:"Transmutado Tipo 3",
    TT3desc:"Transmutados de comida. Casi la mayor variedad, ¡tienes de todo!",
    NCT1title:"No Carbonoide Tipo 1",
    NCT1desc:"No carbonoides de elementos puros, compuestos sencillos y metales. Ahora ser de plata no te molestará.",
    NCT2title:"No Carbonoide Tipo 2",
    NCT2desc:"No carbonoides de compuestos orgánicos. Eres una fábrica andante de tu material, y quizás de algunos otros",
    NCT3title:"No Carbonoide Tipo 3",
    NCT3desc:"No carbonoides de comida. ¡No puedes tener mono de tu comida favorita si estás hecho de ella!",
    alturaEnanatitle:"Minúsculo",
    alturaEnanadesc:"Te nos vas a quedar como mucho en el medio metro. ¡Cuidado con las ratas!",
    alturaPequeñatitle:"Pequeño",
    alturaPequeñadesc:"Con un poco de suerte llegas al metro. Prepárate para que tengas que subirte a hombros de la gente para ver",
    alturaBajatitle:"Bajo",
    alturaBajadesc:"Estás en el rango general de metro-metro y medio. Ahora puedes sentarte a la mesa sin problemas",
    alturaMediatitle:"Medio",
    alturaMediadesc:"Aquí estás en el rango más común, entre uno sesenta y uno noventa. Podrás mirar a la gente a la cara",
    alturaAltatitle:"Alto",
    alturaAltadesc:"Aquí ya nos vamos hasta los dos metros veinte. Destacarás en casi cualquier habitación en la que estés",
    alturaEnormetitle:"Enorme",
    alturaEnormedesc:"Si los dos metros te sabían a poco, ¡ahora llega a los tres! Pero ten cuidado con las puertas, ¿vale?",
    alturaGigantetitle:"Gigante",
    alturaGigantedesc:"¿Cinco metros? Menos mal que puedes controlar tu cuerpo, porque si no estaría complicado encontrar un sitio para vivir",
    constDelgadatitle:"Delgado",
    constDelgadadesc:"No tienes excesivo músculo ni grasa en los huesos. ¿Es una dieta nueva?",
    constIntermediatitle:"Intermedio",
    constIntermediadesc:"Bastante autodescriptivo, vas a estar en el promedio general humano, ni muy delgado ni muy corpulento",
    constEnFormatitle:"En Forma",
    constEnFormadesc:"Tienes una buena cantidad de músculo, y se aprecian sus formas bien bajo la piel",
    constMusculadatitle:"Musculado",
    constMusculadadesc:"Tus músculos están casi a nivel de piel, con una definición impresionante. Con esos bíceps podrías levantar la economía de la Hegemonía",
    constCorpulentatitle:"Corpulento",
    constCorpulentadesc:"Ancho de huesos, achuchable, fuertecito. Hay adjetivos mil, pero tienes un buen cuerpo de padre (o madre)",
    constEsfericatitle:"Esférico",
    constEsfericadesc:"Ahora mismo eres un globo. Quizás te hayan pinchado con un inflador, o hayas inspirado mucho, pero vas rebotando por la vida",
    planatitle:"Pecho plano",
    planadesc:"Plano, plano como una tabla... Una ventaja si no quieres dolores de espalda, o si no quieres dos bolsas de grasa pegadas al pecho. Cada uno a lo suyo.",
    pocoPechotitle:"Poco pecho",
    pocoPechodesc:"Algo de pecho tienes. Aunque mucha gente lo consideraría poco, es el tamaño más práctico para actividades atléticas e ir saltando por ahí.",
    intermediotitle:"Intermedios",
    intermediodesc:"El punto medio perfecto, suficientemente grandes como para que se noten, pero no lo suficiente como para que molesten. Pero, ¿De verdad estamos pensando en practicidad?",
    grandetitle:"Grandes",
    grandedesc:"¡Ya estamos hablando! Dos buenas, grandes y bonitas, perfectas para agarrar y lucirse. ¡Las indicadas para un auténtico fan de las glándulas mamarias!",
    enormestitle:"Enormes",
    enormesdesc:"Vale, cualquier persona te diría que te has pasado, ¡Pero yo no soy cualquier persona! Las tienes tan, o más grandes que tu cabeza. ¡Preciosas, suaves y blanditas! ¡Perfectas para dormir en ellas!",
    dignasDeUnaSantatitle:"Dignas de una Santa",
    dignasDeUnaSantadesc:"Perfección para mucha gente, envidia para otras, absoluta locura para otras. Tienes unas SEÑORAS tetazas, hasta el punto de que igual podrían considerarse más almohadas que partes del cuerpo. Pero eh, si me dejas tocarlas.",
    SANTASTETASDELAMADREtitle:"SANTAS TETAS DE LA MADRE",
    SANTASTETASDELAMADREdesc:"Gigantes, enormes, INCONMENSURABLES. Ahora sí que son almohadas gigantes pegadas a un cuerpo. Difíciles de llevar y cargar. Pero cómo me gustaría dormir en ellas...",
    planotitle:"Sin culo",
    planodesc:"No sé cómo lo has hecho, pero no tienes culo. Tus gluteos son básicamente inexistentes. Tus muslos se unen directamente a tu cadera. No es ni culo carpeta, es... ¿Estás bien?",
    culoCarpetatitle:"Culo carpeta",
    culoCarpetadesc:"Bueno, tienes poco, pero algo tienes. No resaltas nada, nadie te mirará por la calle, ni aunque quieras, pero al menos tienes unas proporciones NATURALES.",
    culitotitle:"Culito",
    culitodesc:"Un culito decentillo y relativamente bien formado. No es muy destacable que digamos, pero es cómodo y suficientemente grande como para ser considerado bonito... para un humano.",
    buenCulotitle:"Buen Culo",
    buenCulodesc:"Mira, ahora sí que te diría que sí a una cena. Tienes un buen culo, bien formado, de buen tamaño y listo para ser agarrado y cacheteado. Pasa rutina y dieta, anda.",
    culazotitle:"Culazo",
    culazodesc:"¡Tremendo culazo! Grande, tonificado, suave y con fuerza. Eres la envidia de cualquier persona normal. Poco más que decir, la verdad, más que eso, TREMENDO CULAAAZOOOOO",
    culoPerfectotitle:"Perfección absoluta culil",
    culoPerfectodesc:"Más que un culazo. La mezcla perfecta de musculatura y grasa para dar lugar a un culo que literalmente será la envidia de cualquier ser. Enorme, pero no demasiado impráctico. Y todas las sillas serán sofás para ti, ¡Qué suerte!",
    asientoPortatiltitle:"Asiento portátil",
    asientoPortatildesc:"Ya no tienes culo, tienes un beanie bag, ya sabes, las bolas estas que se dejan en el suelo y puedes hasta tumbarte en ellas. Tan enorme que puedes sentarte estando de pie, pero moverte debe ser un grano en el culo...",
    muslosPalillotitle:"Palillos",
    muslosPalillodesc:"Ya no es simplemente que siempre te saltes el día de pierna, sino que parece que llevas sin andar meses o años. ¿Puedes andar sin que se te partan las piernas? Habrá que probarlo...",
    muslosPlanostitle:"Planos",
    muslosPlanosdesc:"Sólo te saltas el día de piernas, normal, también te digo, es un puto coñazo... Aún así, no tienes nada que agarrar, de una forma humanamente posible, claro. Haz más ejercicio, por favor.",
    muslosIntermediostitle:"Decentes",
    muslosIntermediosdesc:"Unos muslos y caderas bastante decentillos, nada del otro mundo, pero nada desdeñables. Muy promedio, muy normal, muy... aburrido",
    muslosConCurvastitle:"Buenas Curvas",
    muslosConCurvasdesc:"¡Se notan los meses de gimnasio! O la buena genética, cualquiera de las dos. Tienes buenos muslos y caderas, bastante gente te envidiaría, la verdad",
    muslosChildBearingtitle:"Muslos para repoblar un pueblo moribundo",
    muslosChildBearingdesc:"La envidia de todo el mundo. Tienes unos muslos y unas caderas fuertes, poderosos y con la cantidad justa y necesaria de grasa. Perfección absoluta. ¿Cuándo me vas a reventar a golpes de cadera?",
    muslosFuertestitle:"Parte melones",
    muslosFuertesdesc:"Joder... Por favor, aplástame con esos muslos capaces de partir melones. Apriétame la cabeza hasta que reviente y acabe desparramada por las paredes, por favor...¿De qué estábamos hablando?",
    muslosBloqueaPuertastitle:"Bloquea puertas",
    muslosBloqueaPuertasdesc:"¿Te acuerdas de lo que decía de que lo excesivo era para cobardes? Bueno, te lo has tomado a muslos, por lo que veo. Tienes muslos y caderas tan grandes como alta es una persona. No creo que puedas pasar por ninguna puerta sin reventarla. Pero como se diría en mi pueblo: Si no entra, que raje",
    genitalesVaginatitle:"Vagina",
    genitalesVaginadesc:"Felicidades, ahora tienes lo que la mayor parte de gente del planeta elige tener. ¡Pero sin problema, que a casi todo el mundo le gusta!",
    genitalesClitoristitle:"Clítoris",
    genitalesClitorisdesc:"Una adición razonable en todos los casos, algo tienes que tener para entretenerte en tus ratos libres, ¿eh?",
    genitalesPeneClitoristitle:"Pene clítoris",
    genitalesPeneClitorisdesc:"...no voy a juzgar esto, si te van estas cosas, ¿pero para eso eliges tener pene?",
    genitalesMicropenetitle:"Micropene",
    genitalesMicropenedesc:"Bueno, este por lo menos es más o menos usable. Quizás no te sirva mucho, pero se pueden hacer cosas con él",
    genitalesPenePequeñotitle:"Pene pequeño",
    genitalesPenePequeñodesc:"No entras ya en que tu condición tenga nombre, pero aún así... Míralo por el lado bueno, no se te marcará por debajo de la ropa (si llevas)",
    genitalesPeneMedianotitle:"Pene mediano",
    genitalesPeneMedianodesc:"Hay quien dice que la virtud está en la moderación, ni muy grande ni muy pequeño, justo en el punto",
    genitalesPeneGrandetitle:"Pene grande",
    genitalesPeneGrandedesc:"Aquí ya estamos empezando a hablar. La mayoría de juguetes vienen de este tamaño, así que no te hará competencia un trozo de plástico",
    genitalesPeneEnormetitle:"Pene enorme",
    genitalesPeneEnormedesc:"Con esta arma, podrían detenerte. ¡No tendrás que preocuparte de no saber con qué abrir nueces!",
    genitalesBlostetitle:"El Bloste",
    genitalesBlostedesc:"Y ahora preguntarás, ¿qué es el Bloste? Pues la verdad es que no lo sé. ¿Por qué no le das y lo compruebas?",
    testOvariostitle:"Ovarios",
    testOvariosdesc:"La opción correcta si quieres ser capaz de engendrar descendencia por tu propia cuenta, como yo.",
    testInexistentestitle:"Inexistentes",
    testInexistentesdesc:"A fin de cuentas, ¿quién querría tener una debilidad tan abierta?",
    testInternostitle:"Internos",
    testInternosdesc:"Buena opción, si aún quieres, y te facilita la producción de gametos",
    testPequeñostitle:"Pequeños",
    testPequeñosdesc:"A ver, no puedo decir nada, ¿pero has estado abusando de la testosterona de la Hegemonía?",
    testMedianostitle:"Medianos",
    testMedianosdesc:"Un tamaño adecuado. No quedarán demasiado fuera de lugar a menos que haya una diferencia de tamaño importante con el pene",
    testGrandestitle:"Grandes",
    testGrandesdesc:"Buenas bolas, buen tamaño, buena consistencia... Aunque un poco grandes para mi gusto",
    testEnormestitle:"Enormes",
    testEnormesdesc:"Joder, con unos de ese tamaño, estoy bastante segura de que podrías ahogar a alguien",
    MusculosReforzadostitle:"Músculos reforzados",
    MusculosReforzadosdesc:"Debido a un entrenamiento de alta intensidad o una modificación al maleabilizarte, tus capacidades físicas ahora están por las nubes",
    MejorSistemaNerviosotitle:"Sistema nervioso optimizado",
    MejorSistemaNerviosodesc:"Quizás has hecho muchos sudokus o te has hecho con órganos de la doctora Tiff, pero ahora tu memoria, atención, y procesamiento se han disparado",
    ControlCorporalAvanzadotitle:"Control corporal avanzado",
    ControlCorporalAvanzadodesc:"Es cierto que la gente maleable puede hacer casi lo que quiera con su cuerpo, ¡pero con esto te será más natural y fácil!",
    lnHegemoniatitle:"La Hegemonía",
    lnHegemoniadesc:"El último baluarte de la humanidad... es un sitio decadente lleno de odio y miseria. Siempre bajo la atenta mirada del Gran Hegemón y dispuestos a defenderse con uñas y dientes de lo que, según la propaganda, son horrorosos monstruos comehumanos (Joder, ya sé que no damos muy buena imagen, pero tan malos no somos, ¿No?)",
    lnLibertastitle:"Libertas",
    lnLibertasdesc:"El centro de toda la actividad del mundo, una ciudad cosmopolita que reune a gente de todos lados ya no del mundo, ¡Sino del universo! Es conocida por sus universidades, laboratorios destinados a la investigación de formas de vida maleables y por acoger a cualquier persona que quiera estar ahí por libre decisión. (Yo vivo y trabajo allí, por cierto, ¡Saludos desde Libertas!)",
    lnLechoDeSantatitle:"Lecho de la Santa",
    lnLechoDeSantadesc:"(DISCLAIMER: LEGALMENTE NO PUEDO SER IMPARCIAL) Actual (Y única a lo largo de la historia) sede de la Congregación de las Hermanas de Santa Megumi. El Lecho es altamente conocido por lo peculiar de su fauna y flora basadas en tentáculos y serpientes, además de porque todos los edificios están conectados por barras, grietas y ganchos para que las plasmoides tipo 1 puedan saltar, balancearse y rebotar. ¡También es el centro médico en el que se reúnen las mayores eminencias en cualquier tipo de disciplina! (Y si quieres tener la noche de tu vida, créeme, este es tu sitio)",
    lnPalasextitle:"El Palasex",
    lnPalasexdesc:"A ver, técnicamente no es un país per se, pero sí que es una zona políticamente independiente... Bueno, este sitio es básicamente un mega parque de atracciones en el que LITERALMENTE te puedes encontrar de todo, desde cangrejoides de más allá de La Llama buscando nuevos vínculos hasta fanáticos de un tipo muy específico de terror de Edén de hace milenios, ¡Y todos ellos con su zona delimitada!",
    lnElFervortitle:"El Fervor",
    lnElFervordesc:"El país con la historia, cultura y todo en general, más longevo de este mundo (Coño y tanto, como que lleva 3000000 años existiendo, no te jode). Principalmente poblado por plasmoides tipo 3, por lo que mucha de la arquitectura está basada en tuberías, canales y ríos por los que alguien líquido puede simplemente fluir (Algún día tendría que probarlo...). Ah, y es la zona con más conocimiento arcano y espiritista del mundo. ¡Todo el mundo es un elementalista!",
    lnBiuTauOrtitle:"BiuTau Oriental",
    lnBiuTauOrdesc:"Una zona marcada por el conflicto con sus vecinos occidentales (En realidad sólo se han peleado un par de veces por un río medio congelado, así que...). Irrigado por el río BiuTau y cubierto de pantanos y junglas de plantas y seres gelatinosos, este es el sitio ideal para una plasmoide tipo 2. ¡Ten cuidado y no te estampes con los árboles!",
    lnBiuTauOcctitle:"BiuTau Occidental",
    lnBiuTauOccdesc:"Una zona marcada por el conflicto con sus vecinos orientales (Estos son los que suelen atacar más, por cierto, por eso el río está medio congelado...). Irrigado por el río BiuTau y cubierto por una frondosa selva congelada hasta arriba de nievorilas, ranárboles de chocolate y demás flora y fauna helada, por lo que es el asentamiento perfecto para las transmutadas y no carbonoides de materiales congelados (O si te gusta el helado, claro).",
    lnArchipielagotitle:"Archipiélago de los Santos",
    lnArchipielagodesc:"Curiosamente, no hay mucha gente que haya visitado este pequeño archipiélago gobernado por los Santos Zoo'Mani. Lo único que sabemos es que tienen una cultura basada en los 'deportes de contacto', lo que normalmente se reduce a una glorificación de la violencia en busca de la emoción de la confrontación... ¡Pero eh, su gente es majísima si no te dejas intimidar por sus formas medio animales!  ",
    lnEnclavestitle:"Enclaves Libres",
    lnEnclavesdesc:"Un conjunto de pequeños estados federales llamados distritos, cada uno de ellos dedicado a la manufactura y el comercio de un tipo de mercancía distinto. Este país gobernado por El Don de los Enclaves se fundó como un refugio para la gente que escapó de la Hegemonía durante la rebelión fallida y de las fábricas de Hall&Co. Se come de puta madre y se vive mejor, honestamente, ¡Por algo es la segunda zona más variada del mundo!",
    lnGranEmporiotitle:"Gran Emporio de Hall",
    lnGranEmporiodesc:"Lo siento, de verdad que lo siento... Si has nacido aquí, huye, si vives aquí, huye. Da igual lo que seas, si estás aquí mucho tiempo, serás poco más que una máquina expendedora más que ordeñar. No se puede decir que este sitio tenga población, sino eso, recursos humanos que serán explotados por el chocolateado puño de Hellen Hall.",
    lnOasistitle:"El Oasis",
    lnOasisdesc:"¡Mira, un buen sitio para vivir! Fundado por la Doctora Tiffanny y las supervivientes de las fábricas de Hall&Co, este es un auténtico remanso de paz para las no carbonoides tipo 3, lleno de fauna y flora dulce y abundante para asegurar su autonomía. ¡El sitio perfecto para unas vacaciones y para cagarte en los muertos de la gente que te ha esclavizado!",
    lnTimarAurhumtitle:"Timar Aurhum",
    lnTimarAurhumdesc:"El país con mayor poder militar del oeste, fundado por el Gran Rey Aureliano tras la rebelión fallida en las cuevas occidentales influenciadas por el núcleo de la protección y el metal. Actualmente es una monarquía absolutista en la que poco puedes hacer si quieres algo de privacidad, ¡Pero eh, puedes ver arañas de cristal y dragones de metal gigantes con cuatro puños (Están guapísimos los Geidures, ¿A que sí?)!",
    lrHegemoniatitle:"La Hegemonía",
    lrHegemoniadesc:"El último baluarte de la humanidad... es un sitio decadente lleno de odio y miseria. Siempre bajo la atenta mirada del Gran Hegemón y dispuestos a defenderse con uñas y dientes de lo que, según la propaganda, son horrorosos monstruos comehumanos (Joder, ya sé que no damos muy buena imagen, pero tan malos no somos, ¿No?)",
    lrLibertastitle:"Libertas",
    lrLibertasdesc:"El centro de toda la actividad del mundo, una ciudad cosmopolita que reune a gente de todos lados ya no del mundo, ¡Sino del universo! Es conocida por sus universidades, laboratorios destinados a la investigación de formas de vida maleables y por acoger a cualquier persona que quiera estar ahí por libre decisión. (Yo vivo y trabajo allí, por cierto, ¡Saludos desde Libertas!)",
    lrLechoDeSantatitle:"Lecho de la Santa",
    lrLechoDeSantadesc:"(DISCLAIMER: LEGALMENTE NO PUEDO SER IMPARCIAL) Actual (Y única a lo largo de la historia) sede de la Congregación de las Hermanas de Santa Megumi. El Lecho es altamente conocido por lo peculiar de su fauna y flora basadas en tentáculos y serpientes, además de porque todos los edificios están conectados por barras, grietas y ganchos para que las plasmoides tipo 1 puedan saltar, balancearse y rebotar. ¡También es el centro médico en el que se reúnen las mayores eminencias en cualquier tipo de disciplina! (Y si quieres tener la noche de tu vida, créeme, este es tu sitio)",
    lrPalasextitle:"El Palasex",
    lrPalasexdesc:"A ver, técnicamente no es un país per se, pero sí que es una zona políticamente independiente... Bueno, este sitio es básicamente un mega parque de atracciones en el que LITERALMENTE te puedes encontrar de todo, desde cangrejoides de más allá de La Llama buscando nuevos vínculos hasta fanáticos de un tipo muy específico de terror de Edén de hace milenios, ¡Y todos ellos con su zona delimitada!",
    lrElFervortitle:"El Fervor",
    lrElFervordesc:"El país con la historia, cultura y todo en general, más longevo de este mundo (Coño y tanto, como que lleva 3000000 años existiendo, no te jode). Principalmente poblado por plasmoides tipo 3, por lo que mucha de la arquitectura está basada en tuberías, canales y ríos por los que alguien líquido puede simplemente fluir (Algún día tendría que probarlo...). Ah, y es la zona con más conocimiento arcano y espiritista del mundo. ¡Todo el mundo es un elementalista!",
    lrBiuTauOrtitle:"BiuTau Oriental",
    lrBiuTauOrdesc:"Una zona marcada por el conflicto con sus vecinos occidentales (En realidad sólo se han peleado un par de veces por un río medio congelado, así que...). Irrigado por el río BiuTau y cubierto de pantanos y junglas de plantas y seres gelatinosos, este es el sitio ideal para una plasmoide tipo 2. ¡Ten cuidado y no te estampes con los árboles!",
    lrBiuTauOcctitle:"BiuTau Occidental",
    lrBiuTauOccdesc:"Una zona marcada por el conflicto con sus vecinos orientales (Estos son los que suelen atacar más, por cierto, por eso el río está medio congelado...). Irrigado por el río BiuTau y cubierto por una frondosa selva congelada hasta arriba de nievorilas, ranárboles de chocolate y demás flora y fauna helada, por lo que es el asentamiento perfecto para las transmutadas y no carbonoides de materiales congelados (O si te gusta el helado, claro).",
    lrArchipielagotitle:"Archipiélago de los Santos",
    lrArchipielagodesc:"Curiosamente, no hay mucha gente que haya visitado este pequeño archipiélago gobernado por los Santos Zoo'Mani. Lo único que sabemos es que tienen una cultura basada en los 'deportes de contacto', lo que normalmente se reduce a una glorificación de la violencia en busca de la emoción de la confrontación... ¡Pero eh, su gente es majísima si no te dejas intimidar por sus formas medio animales!  ",
    lrEnclavestitle:"Enclaves Libres",
    lrEnclavesdesc:"Un conjunto de pequeños estados federales llamados distritos, cada uno de ellos dedicado a la manufactura y el comercio de un tipo de mercancía distinto. Este país gobernado por El Don de los Enclaves se fundó como un refugio para la gente que escapó de la Hegemonía durante la rebelión fallida y de las fábricas de Hall&Co. Se come de puta madre y se vive mejor, honestamente, ¡Por algo es la segunda zona más variada del mundo!",
    lrGranEmporiotitle:"Gran Emporio de Hall",
    lrGranEmporiodesc:"Lo siento, de verdad que lo siento... Si has nacido aquí, huye, si vives aquí, huye. Da igual lo que seas, si estás aquí mucho tiempo, serás poco más que una máquina expendedora más que ordeñar. No se puede decir que este sitio tenga población, sino eso, recursos humanos que serán explotados por el chocolateado puño de Hellen Hall.",
    lrOasistitle:"El Oasis",
    lrOasisdesc:"¡Mira, un buen sitio para vivir! Fundado por la Doctora Tiffanny y las supervivientes de las fábricas de Hall&Co, este es un auténtico remanso de paz para las no carbonoides tipo 3, lleno de fauna y flora dulce y abundante para asegurar su autonomía. ¡El sitio perfecto para unas vacaciones y para cagarte en los muertos de la gente que te ha esclavizado!",
    lrTimarAurhumtitle:"Timar Aurhum",
    lrTimarAurhumdesc:"El país con mayor poder militar del oeste, fundado por el Gran Rey Aureliano tras la rebelión fallida en las cuevas occidentales influenciadas por el núcleo de la protección y el metal. Actualmente es una monarquía absolutista en la que poco puedes hacer si quieres algo de privacidad, ¡Pero eh, puedes ver arañas de cristal y dragones de metal gigantes con cuatro puños (Están guapísimos los Geidures, ¿A que sí?)!",
    faccHegemoniatitle:"Hegemonía de todos los Hombres",
    faccHegemoniadesc:"Vale, de verdad, no sé qué coño haces usando esto. ¿Qué? ¿Tu amo Smith te ha soltado de la correa y te ha permitido meterte en la red de fuera del país? Bueno, si es así... Ya sabes lo que hay, un grupo de fanáticos extremistas que odian cualquier cosa que no sea humana. ¿Qué eres, un currito más bajo la opresión del Hegemón, un inspector, UNA LUZ DE GAS...? O igual quieres cambiar las cosas desde dentro...",
    faccLaboratoriostitle:"Laboratorios Riuter",
    faccLaboratoriosdesc:"Sé que ya he dicho que no puedo ser imparcial, pero, joder, es que trabajo allí... Los Laboratorios Riuter son el centro más prestigioso (El único) de investigación de formas de vida maleables en todo Aelfatum. Presididos por la Doctora Yulva Maltarum (LA JEFA), el Doctor Anthony Gums (DON JEFE) y, últimamente, la Doctora Camelia Thomson. Pues eso, que es un sitio en el que trabajamos para descubrir los secretos de lo maleable. ¡Únete a nosotras, estira tus límites (El eslogan cursi también era obligatorio)!",
    faccHermanastitle:"Congregación de las Hermanas de Santa Megumi de la Vida y Su Elástica Faz",
    faccHermanasdesc:"La otra facción de una servidora y la que literalmente me salvó la vida. Son un conjunto de pequeños conventos, cada uno presidido por una santa distinta, desde Katarina hasta Ophelia. Aún así, esta congregación centrada en el servicio a las demás, la medicina, la sanación y aumentar la población y el placer en el mundo, hoy en día está 'gobernada' por la Gran Santa Megumi de la Vida y gobernada por su madre, Santa Alicia del Vacío. Si quieres echar un buen polvo, ayudar a la gente y encima que te ayuden, ¡Este es tu sitio! ",
    faccFervortitle:"Elementalistas del Fervor",
    faccFervordesc:"¡Las mayores expertas en espiritismo y ciencia intrasencial del planeta! ¿Qué coño del planeta? DE LA GALAXIA. Hace mucho tiempo eran cinco países distintos, pero todos se acabaron uniendo en una única facción tras la Ascensión de Sanabaur. En resumen, mucha Intra, muchos elementos y mucho vino, ¡Todo ello bajo la atenta mirada de La Tejedestinos en persona (Atenta siempre que no esté como una puta cuba, claro)!",
    faccAprendizastitle:"Aprendizas de Azxqerfo",
    faccAprendizasdesc:"¿Te gustan las artes marciales, las enfermedades y los árboles? ¿Quieres aprender las bondades de meterte un clavo por el culo? ¿Te apetecería probar suerte con LA PIEDRA MÁGICA DEL CONTROL? ¡Pues pídele cita al Doctor Azxqerfo y deja que te entrene junto a eminencias de la lucha como Bea, Bea y... BEA! De aquí sale la gran mayoría del personal médico del sur del planeta, eso sí, te advierto que su definición de curar es... poco ortodoxa",
    faccOasistitle:"Supervivientes del Oasis",
    faccOasisdesc:"Ufff, esta es dura, por lo que veo. Todas las personas de esta facción son esclavas fugadas de las fábricas de Hall que han podido fundar su propio país en el BiuTau Occidental. Es una facción basada en la cooperación, la libertad y el amor por una vida individual justa. Y parece que todo va perfectamente, bueno, todo lo bien que puede irle a un estado recién formado. Pero Tiff hace lo que puede (Por las gomosas tetas de La Madre, qué orgullosas estamos de ella).",
    faccHallYCotitle:"Hall &Co: Foods And Experiences",
    faccHallYCodesc:"¿Seguís existiendo hoy en día? Pensaba que después de lo que le pasó a vuestra je... Ehem. Hall&Co, Hall&Co... La empresa que monopolizó la producción de cualquier producto que podría extraerse de una maleable... Mediante la esclavitud de personas a las que ordeñaba como si fueran básicamente bhures o frutas. Si te gusta el dinero, la esclavitud y la explotación (Además de reducir y torturar tanto a las personas que literalmente dejan de considerarse personas a sí mismas), esta es tú facción, supongo...",
    faccEnclavestitle:"Enclaves Libres",
    faccEnclavesdesc:"La facción más hetereogénea y variada de todas. Dividida en capitanías que funcionan como una máquina perfectamente engrasada bajo la atenta mirada y apoyo del Don de los Enclaves. ¿Quieres cocinar? ¡Ve al distrito de la restauración! ¿Quieres producir químicos? ¡PhlecksChem te recibirá con los brazos abiertos! ¿Quieres un par de tragos? ¡El Bubble's siempre está abierto y Gums siempre estará ahí para ti! Eso sí, recuerda pagar tus impuestos y responder a los llamados de auxilio de la gente a tu alrededor, o podría ser que nadie responda a los tuyos.",
    faccTimarAurhumtitle:"Ejército Dorado de Timar Aurhum",
    faccTimarAurhumdesc:"¡Honrada, fuerte, poderosa y profesional! Así es como se define a sí misma la gente de Timar Aurhum (Se suelen olvidar de la parte del palo metido por el culo, pero bueno). Este orgulloso pueblo de soldados, herreros y mineros está hoy en día dividido por un conflicto de sucesión. La gente tiene que decidir si apoyar al Rey Aureliano, fundador del país y gobernante absoluto expansionista del mismo, o a su hija, la Princesa Electra, que aboga por afrontar las relaciones exteriores con un enfoque más diplomático, por decirlo de alguna forma. ¿Qué eligirías tú?"
}