const datos_ENG ={
    Género:"Gender",
    Especie:"Species",
    Subespecie:"Subespecies",
    FormaDeVida:"Lifeforms",
    Material:"Material",
    Altura:"Height",
    Constitucion:"Constitution",
    Pechos:"Chest size",
    Culo:"Ass size",
    Muslos:"Hips and thighs size",
    Genitales:"Genitals",
    Testículos:"Testicles size",
    ModificacionesCorporales:"Body modifications",
    LugarDeNacimiento:"Place of birth",
    LugarDeResidencia:"Place of residence",
    Faccion:"Faction",
    Masculinotitle:"Masculine",
    Masculinodesc:"You're a masculine being",
    Femeninotitle:"Feminine",
    Femeninodesc:"You're a feminine being",
    "No-Binarietitle":"Non binary",
    "No-Binariedesc":"You're a non binary being",
 Humanotitle:"Human",
    Humanodesc:"You're a human. It's objectively the worst decision, but, hey, you have more points to spend!",
    Plasmoidetitle:"Plasmoid",
    Plasmoidedesc:"You're a Plasmoid. Your species has a segmented skeleton and, thanks to some complex physical systems, you can change your shape and general body structure",
    Transmutadotitle:"Transmuted",
    Transmutadodesc:"You're a Transmuted. You don't have any structure, as you're just a mass of your material that can take any shape or form",
    "No-Carbonoidetitle":"Non Carbonoid",
    "No-Carbonoidedesc":"You're a Non Carbonoid. You have internal structure, just like a plasmoid has, but adapted to your own material, so you get the most out of it.",
    PT1title:"Type 1 Plasmoid",
    PT1desc:"Known for their elastic and malleable body at room temperature, they're the most \"solid\" option out of the three",
    PT2title:"Type 2 Plasmoid",
    PT2desc:"Known for their viscous and gelatinous body at room temperature, you may leave some residue wherever you go",
    PT3title:"Type 3 Plasmoid",
    PT3desc:"Known for their fluid and liquid body at room temperaature, you'll have to be a bit careful not to go down the drains",
    PT0title:"Type 0 Plasmoid",
    PT0desc:"A very rare variant, able to modify their state at will",
    TT1title:"Type 1 Transmuted",
    TT1desc:"Transmuted made from pure elements, simple compounds and metals, from gold up to some explosives",
    TT2title:"Type 2 Transmuted",
    TT2desc:"Transmuted made from organic compounds, in case you've ever wanted to be a protein, or made from alcohol",
    TT3title:"Type 3 Transmuted",
    TT3desc:"Food-based Transmuted. They almost have the most variety, you have everything!",
    NCT1title:"Type 1 Non-Carbonoid",
    NCT1desc:"Non-Carbonoids made from pure elements, simple compounds and metals. Now being made of silver won't trouble you",
    NCT2title:"Type 2 Non-Carbonoid",
    NCT2desc:" Non-Carbonoid made from organic compounds. You're a walking generator of your own material, and maybe of some others",
    NCT3title:"Type 3 Non-Carbonoid",
    NCT3desc:"Food-based Non-Carbonoids. Can't crave your favorite food if you're made out of it!",
    alturaEnanatitle:"Tiny",
    alturaEnanadesc:"You're going to be at most like half a meter tall. Beware the rats!",
    alturaPequeñatitle:"Small",
    alturaPequeñadesc:"With a bit of luck, you'll reach a meter of height. Get prepared to have to get on people's shoulders to see stuff",
    alturaBajatitle:"Short",
    alturaBajadesc:"You're between a meter and a meter and a half. Now you can sit on the table with no trouble",
    alturaMediatitle:"Medium",
    alturaMediadesc:"Now you're in a more common range, between 1,60m and 1,90m. You'll be able to talk to people face-to-face",
    alturaAltatitle:"Tall",
    alturaAltadesc:"Here, we reach 2,20m. You'll stand out in any room you're in",
    alturaEnormetitle:"Huge",
    alturaEnormedesc:"If two meters felt short to you, now you'll reach the three meter mark! But be careful with the doors, alright?",
    alturaGigantetitle:"Gigantic",
    alturaGigantedesc:"Five meters? It's a relief you can control your body, because it would be difficult finding a place to live otherwise",
    constDelgadatitle:"Thin",
    constDelgadadesc:"You don't have excessive muscle nor fat on your bones. Is it a new diet?",
    constIntermediatitle:"Intermediate",
    constIntermediadesc:"Pretty autodescriptive, you'll be in the human average, not too thin, not too bulky",
    constEnFormatitle:"Fit",
    constEnFormadesc:"You have a nice ammount of muscle, and their shape can be seen under the skin",
    constMusculadatitle:"Toned",
    constMusculadadesc:"Your muscles are almost at skin level, with some impressive definition. With those biceps you could lift the Hegemony's economy",
    constCorpulentatitle:"Hefty",
    constCorpulentadesc:"Big boned, huggable, plump. There are a thousand adjetives, but you have a nice dad (or mom) bod",
    constEsfericatitle:"Spherical",
    constEsfericadesc:"Right now, you are a balloon. Maybe you've been stabbed with an inflator, or may have inhaled too strongly, but you'll be bouncing around",
    planatitle:"Flat chest",
    planadesc:"Flat, flat as a plank... An advantage, if you don't want back pain, or if you don't want two fat balls on your chest. To each their own",
    pocoPechotitle:"Small chest",
    pocoPechodesc:"You have some chest. Even though many people would consider it little, it is the most practical size for athletics and jumping around",
    intermediotitle:"Intermediate",
    intermediodesc:"The perfect middleground, big enough to be noticed and small enough not to be a burden. But, are we realy thinking about practicity here?",
    grandetitle:"Grandes",
    grandedesc:"Now we're talking! Good, big, and beautiful, perfect for grabbing and showing off. Suitable for a true mammarie glands' fan!",
    enormestitle:"Enormous",
    enormesdesc:"Alright, some people would say you've gone too far, but I'm not some people! They are as big as, or bigger than, your head. Pretty, soft and squishy! Perfect for sleeping on them!",
    dignasDeUnaSantatitle:"Worthy of a Saint",
    dignasDeUnaSantadesc:"Perfection for some people, jealusy for others, pure craziness for some others. You have some BIG boobs, so much so that they may be closer to pillows than part of your body. But, hey, if you let me touch 'em...",
    SANTASTETASDELAMADREtitle:"MOTHER'S HOLY RUBBERY TITS",
    SANTASTETASDELAMADREdesc:"Gigantic, enormous, IMMEASURABLE. Now they really are two giant pillows attached to your body. Difficult to lift and carry. But I would love to sleep on them...",
    planotitle:"Buttless",
    planodesc:"I don't know how you've done this, but you don't have a butt. Your buttocks are barely inexistent. Your thighs connect directly with your hips. It's not even a flat ass, it's... Are you alright?",
    culoCarpetatitle:"Flat ass",
    culoCarpetadesc:"Well, you have little ass, but you have something. You don't stand out, nobody will look at you while outside, not even if you want to, but you at least have some NATURAL proportions.",
    culitotitle:"Small ass",
    culitodesc:"A nice little ass, and relatively well formed. It's not very notable, let's say, but it's comfortable and big enough to be called pretty... for a human.",
    buenCulotitle:"Nice ass",
    buenCulodesc:"Look, now I would accept having dinner with you. You have a nice ass, very well formed, nice size, and ready to be grabbed and spanked. Send your exercise routine and diet, c'mon",
    culazotitle:"Big ass",
    culazodesc:"Tremendous ass! Big, toned, soft and strong. Normal people will envy you. There is very little to say apart from that, TREMENDOUS ASS.",
    culoPerfectotitle:"Absolute buttal perfection",
    culoPerfectodesc:"Even more than a perfectt butt. The perfect mix of musculature and fat which results in an ass that will make any being envy you. Enormous, but not very impractical. And all chairs will be sofas for you. Lucky you!",
    asientoPortatiltitle:"Portable seat",
    asientoPortatildesc:"You don't even have an ass anymore, you have a beanie bag, you know, those balls you put on the floor and can even lay on them. SO big you can even sit standing up, but moving around must be a pain in the ass...",
    
    muslosPalillotitle:"Sticks",
    muslosPalillodesc:"Now, you don't only skip leg day, but you look like you haven't done any proper walking in months or even years. Can you even walk without your legs snapping? Guess you'll have to see it for yourself...",
    muslosPlanostitle:"Flat",
    muslosPlanosdesc:"You just skip leg day, understandable, not gonna lie, it's so fucking boring... Even so, you don't have any meat to be grabbed, in a human way, at least. Do more exercise, please. ",
    muslosIntermediostitle:"Decent",
    muslosIntermediosdesc:"Some pretty decent thighs and hips, nothing out of the ordinary, but they aren't too bad either. Pretty common, very average, so... boring",
    muslosConCurvastitle:"Some nice curves",
    muslosConCurvasdesc:"The months in the gym are finally paying out! Or the good genes, whichever it is. You have good hips and thighs, most people would envy you, to be honest",
    muslosChildBearingtitle:"Hips to revive a dying civilization",
    muslosChildBearingdesc:"Everyone envies you. You have some strong and powerful thighs and hips with the perfect amount of fat. Absolute perfection. So... When are you going to smash me with them?",
    muslosFuertestitle:"Melon smashers",
    muslosFuertesdesc:"Holy fuck... Please, smash me with those thighs capable of destroying melons. Squash my head until it explodes and I end up as nothing but a splatter on the walls, please... What were we talking about?",
    muslosBloqueaPuertastitle:"Door blockers",
    muslosBloqueaPuertasdesc:"You remember what I told you that considering things excesive was for cowards? Well, you seem to have taken it to the hips. You have thighs and hips as wide as tall is a person. I'm not sure if you can go through a door without demolishing it. But as we say in my town: If it doesn't fit, let it rip.",
    genitalesVaginatitle:"Vagina",
    genitalesVaginadesc:"Congratulations, you now have what most of the people in this planet chooses to have. But don't worry, almost everybody likes it!",
    genitalesClitoristitle:"Clitoris",
    genitalesClitorisdesc:"A reasonable addition to every case, you need something to play with in your free time, don't you?",
    genitalesPeneClitoristitle:"Clit penis",
    genitalesPeneClitorisdesc:"... Look, I'm not gonna judge you for this, if you like it. But wouldn't you rather have a proper penis?",
    genitalesMicropenetitle:"Micropenis",
    genitalesMicropenedesc:"I mean, at least it's more or less usable. It may not be really useful, but you can make it work",
    genitalesPenePequeñotitle:"Small penis",
    genitalesPenePequeñodesc:"You don't have any kind of medical condition, but... Look at the bright side, it wouldn't show through your clothes (If you wear any)",
    genitalesPeneMedianotitle:"Medium penis",
    genitalesPeneMedianodesc:"Some people say that medium is premium, not too big, not too small, just in the middle",
    genitalesPeneGrandetitle:"Big penis",
    genitalesPeneGrandedesc:"Now we're talking. Most toys come in this size, so you won't have to compete with a piece of plastic",
    genitalesPeneEnormetitle:"Gigantic penis",
    genitalesPeneEnormedesc:"You could be arrested with such a weapon. And you won't have to worry about cracking nuts!",
    genitalesBlostetitle:"The Mahug",
    genitalesBlostedesc:"And now you'll ask, what's Mahug? I really don't know. Why don't you click this and find out?",
    testOvariostitle:"Ovaries",
    testOvariosdesc:"The right option if you want to be able to have children on your own, just like me.",
    testInexistentestitle:"Non existant",
    testInexistentesdesc:"Who would want to have such an obvious weak spot?",
    testInternostitle:"Internal",
    testInternosdesc:"Nice choice, if you still want them, and it will even make the production of gametes easier.",
    testPequeñostitle:"Small",
    testPequeñosdesc:"Don't worry, I won't tell anyone. Have you been taking testosterone from the Hegemony or something?",
    testMedianostitle:"Medium",
    testMedianosdesc:"An adequate size. They won't seem out of place as long as the rest of things are in proportion",
    testGrandestitle:"Big",
    testGrandesdesc:"Nice balls, good size, better consistency... A bit too big for my liking, though.",
    testEnormestitle:"Enormous",
    testEnormesdesc:"Holy cores, I'm pretty sure you can smother someone with those.",
    MusculosReforzadostitle:"Armored muscles",
    MusculosReforzadosdesc:"Due to either high intensity training or a maleable modification, your physical capabilities are now off the charts.",
    MejorSistemaNerviosotitle:"Optimized nervous system",
    MejorSistemaNerviosodesc:"You may have done a lot of sudokus, or snatched some new organs from Doctor Tiff's lab, but now your memory, focus and processing speed have improved a whole lot",
    ControlCorporalAvanzadotitle:"Advanced body control",
    ControlCorporalAvanzadodesc:"Everyone knows that malleable folk can do whatever they want with their bodies, but with this it will be even easier!",
    lnHegemoniatitle:"The Hegemony",
    lnHegemoniadesc:"Mankind's last resort... is a shithole full of hate and misery. Always under the watch of the Great Hegemon and ready to defend tooth and nail their country from what seem to be, as the propaganda says, some terrifying maneater monsters (Cores, I know we don't care a lot for our PR, but we're not that bad, right?)",
    lnLibertastitle:"Libertas",
    lnLibertasdesc:"The neuralgical center of the world, a cosmopolitan city that gathers people from all around, not only the world, but the Universe! It's famous for its universities, laboratories dedicated to the research of malleable life forms and letting everyone willing to get in. (I live and work there, if you didn't know, Greetings from Libertas!",
    lnLechoDeSantatitle:"Saint's Bed",
    lnLechoDeSantadesc:"(DISCLAIMER: I LEGALLY CAN'T BE UNBIASED) Current (And the only one in history) headquarters of the Congregation of the Sisters of Saint Megumi. The Bed is known for its peculiar fauna and flora based on tentacles and snakes, oh, and for the bars, slits and hooks they put all over the place so the type 1 plasmoids can jump, swing and bounce from place to place. It is also the medical center where you can find the best experts in any discipline! (And if you want to have the night of your life, believe me, this is also your place)",
    lnPalasextitle:"The Palasex",
    lnPalasexdesc:"Well, this isn't really a country, but a politically independent zone... So, this place is basically a huge amusement park in which you can found LITERALLY anything, from craboids from far beyond The Flame looking for some new spirits to bind to people addicted to a very specific kind of horror from Eden that was lost milennia ago, all of them in their own little zone!",
    lnElFervortitle:"The Zeal",
    lnElFervordesc:"The country with the most history, culture and everything in general, which is also the oldest in the world (Of course, it has been existing for like 3000000 years, for fucks sake). Mainly inhabited by type 3 plasmoids, so most of the architecture is based on pipes, channels and rivers in which liquid people can just flow (I should try that someday...). Oh, and it's also the zone with the most arcane and spiritual knowlege in the world. Everyone's an elementalist!",
    lnBiuTauOrtitle:"Eastern BiuTau",
    lnBiuTauOrdesc:"A country scarred by the conflict they have with their western neighbours (They just had some fights for a half frozen river, so...). Blessed by the waters of the BiuTau river and covered in swamps and jungles full of slimy plants and beings, the perfect place for a type 2 plasmoid. Please be careful not to slam face first on a tree!",
    lnBiuTauOcctitle:"Western BiuTau",
    lnBiuTauOccdesc:"A country scarred by the conflict they have with their eastern neighbors (This tend to attack more, just as a fact, due to the river being half frozen and such...) Blessed by the waters of the BiuTau river and covered with a dense icy jungle full to the brim with snowrilas, chocolate frogtrees and more frozen flora and fauna, so this is the perfect settlement for transmuted and non carbonoids made of cold materials (Or if you like ice cream)",
    lnArchipielagotitle:"The Saints Archipelago",
    lnArchipielagodesc:"The crib of many civilizations and countries (Don't worry, I'm not going to bore you with historical dramas and migratory conflicts). What I can actually say is that they have a culture based on clans and 'contact sports', which almost always end up being a glorification of violence in search of the thrill of the fight... But they are really nice people, if you're not intimidated by their feral looks!",
    lnEnclavestitle:"Free Enclaves",
    lnEnclavesdesc:"A Union of little federal states called districts, each of them dedicated to crafting and trading a specific kind of products. This country ruled by The Don of The Enclaves was founded as a safe haven for the people who fleed the tyranny of the Archipelago during MayYahn's revolution, and due to that is now regarded as a source of hope for the people who want to oppose the Hegemony or Hall&Co. The food is great and the living conditions are better, if I may say so myself, it isn't the second most varied zone in the world for nothing!",
    lnGranEmporiotitle:"Hall's Great Emporium",
    lnGranEmporiodesc:"I'm sorry, I'm really sorry... If you were born here, get out, if you live there, get out. It doesn't matter what you are, if you're here long enough you'll end up as one more vending machine to be milked. This place doesn't have population per se, but it has that, human resources to be exploited by the chocolatey fist of Hellen Hall.",
    lnOasistitle:"The Oasis",
    lnOasisdesc:"Oh, look, an actual nice place to live in! Founded by Doctor Tiffanny and the survivors of Hall&Co's factories, this place is a true peaceful paradise for type 3 non carbonoids, full of sweet fauna and flora to keep its autonomy safe. The perfect place for a vacation and hating the guts of the people that have enslaved you!",
    lnTimarAurhumtitle:"Timar Aurhum",
    lnTimarAurhumdesc:"The most militaristic of the western hemisphere, founded by Great King Aurelian after the fail rebellion in some caves and grottos influenced by the core of protection and metal. It is right now an absolute monarchy that doesn't value the privacy of its subjects that much. But hey, you can see crystal spiders and ginormous four armed metal dragons! (Geidurs are cool as fuck, aren't they?)",
    lrHegemoniatitle:"The Hegemony",
    lrHegemoniadesc:"Mankind's last resort... is a shithole full of hate and misery. Always under the watch of the Great Hegemon and ready to defend tooth and nail their country from what seem to be, as the propaganda says, some terrifying maneater monsters (Cores, I know we don't care a lot for our PR, but we're not that bad, right?)",
    lrLibertastitle:"Libertas",
    lrLibertasdesc:"The neuralgical center of the world, a cosmopolitan city that gathers people from all around, not only the world, but the Universe! It's famous for its universities, laboratories dedicated to the research of malleable life forms and letting everyone willing to get in. (I live and work there, if you didn't know, Greetings from Libertas!",
    lrLechoDeSantatitle:"Saint's Bed",
    lrLechoDeSantadesc:"(DISCLAIMER: I LEGALLY CAN'T BE UNBIASED) Current (And the only one in history) headquarters of the Congregation of the Sisters of Saint Megumi. The Bed is known for its peculiar fauna and flora based on tentacles and snakes, oh, and for the bars, slits and hooks they put all over the place so the type 1 plasmoids can jump, swing and bounce from place to place. It is also the medical center where you can find the best experts in any discipline! (And if you want to have the night of your life, believe me, this is also your place)",
    lrPalasextitle:"The Palasex",
    lrPalasexdesc:"Well, this isn't really a country, but a politically independent zone... So, this place is basically a huge amusement park in which you can found LITERALLY anything, from craboids from far beyond The Flame looking for some new spirits to bind to people addicted to a very specific kind of horror from Eden that was lost milennia ago, all of them in their own little zone!",
    lrElFervortitle:"The Zeal",
    lrElFervordesc:"The country with the most history, culture and everything in general, which is also the oldest in the world (Of course, it has been existing for like 3000000 years, for fucks sake). Mainly inhabited by type 3 plasmoids, so most of the architecture is based on pipes, channels and rivers in which liquid people can just flow (I should try that someday...). Oh, and it's also the zone with the most arcane and spiritual knowlege in the world. Everyone's an elementalist!",
    lrBiuTauOrtitle:"Eastern BiuTau",
    lrBiuTauOrdesc:"A country scarred by the conflict they have with their western neighbours (They just had some fights for a half frozen river, so...). Blessed by the waters of the BiuTau river and covered in swamps and jungles full of slimy plants and beings, the perfect place for a type 2 plasmoid. Please be careful not to slam face first on a tree!",
    lrBiuTauOcctitle:"Western BiuTau",
    lrBiuTauOccdesc:"A country scarred by the conflict they have with their eastern neighbors (This tend to attack more, just as a fact, due to the river being half frozen and such...) Blessed by the waters of the BiuTau river and covered with a dense icy jungle full to the brim with snowrilas, chocolate frogtrees and more frozen flora and fauna, so this is the perfect settlement for transmuted and non carbonoids made of cold materials (Or if you like ice cream)",
    lrArchipielagotitle:"The Saints Archipelago",
    lrArchipielagodesc:"The crib of many civilizations and countries (Don't worry, I'm not going to bore you with historical dramas and migratory conflicts). What I can actually say is that they have a culture based on clans and 'contact sports', which almost always end up being a glorification of violence in search of the thrill of the fight... But they are really nice people, if you're not intimidated by their feral looks!",
    lrEnclavestitle:"Free Enclaves",
    lrEnclavesdesc:"A Union of little federal states called districts, each of them dedicated to crafting and trading a specific kind of products. This country ruled by The Don of The Enclaves was founded as a safe haven for the people who fleed the tyranny of the Archipelago during MayYahn's revolution, and due to that is now regarded as a source of hope for the people who want to oppose the Hegemony or Hall&Co. The food is great and the living conditions are better, if I may say so myself, it isn't the second most varied zone in the world for nothing!",
    lrGranEmporiotitle:"Hall's Great Emporium",
    lrGranEmporiodesc:"I'm sorry, I'm really sorry... If you were born here, get out, if you live there, get out. It doesn't matter what you are, if you're here long enough you'll end up as one more vending machine to be milked. This place doesn't have population per se, but it has that, human resources to be exploited by the chocolatey fist of Hellen Hall.",
    lrOasistitle:"The Oasis",
    lrOasisdesc:"Oh, look, an actual nice place to live in! Founded by Doctor Tiffanny and the survivors of Hall&Co's factories, this place is a true peaceful paradise for type 3 non carbonoids, full of sweet fauna and flora to keep its autonomy safe. The perfect place for a vacation and hating the guts of the people that have enslaved you!",
    lrTimarAurhumtitle:"Timar Aurhum",
    lrTimarAurhumdesc:"The most militaristic of the western hemisphere, founded by Great King Aurelian after the fail rebellion in some caves and grottos influenced by the core of protection and metal. It is right now an absolute monarchy that doesn't value the privacy of its subjects that much. But hey, you can see crystal spiders and ginormous four armed metal dragons! (Geidurs are cool as fuck, aren't they?)",
    faccHegemoniatitle:"The Hegemony of All Men",
    faccHegemoniadesc:"Seriously, I don't fucking know what are you doing using this. What is it? Your master Smith has given you a little freedom and has let you get in the net from outside the country? Well, it he did... You know what there is to it, a bunch of extremists who hate everything that isn't human. Now I'm curious. What are you, an office worker being squashed by the boot of the Hegemon, an inspector, A GASLIGHT...? Or maybe you want to change things from within... ",
    faccLaboratoriostitle:"Riuter Laboratories",
    faccLaboratoriosdesc:"I know I've already told you that I can't be unbiased, but, by the Mother, I work there... Riuter Laboratories are the most prestigious (And the only one) center of research for malleable life forms in the face of Aelfatum. Directed by Doctor Yulva Maltarum (THE BOSS), Doctor Anthony Gums (DON BOSS) and, lately, Doctor Camelia Thomson. So, yeah, it's a place where we work to uncovet the secrets of everything malleable. Join us, stretch your limits! (This cheesy slogan was also a contractual obligations)",
    faccHermanastitle:"Congregation of the Sisters of Saint Megumi of Life and Her Elastic Face",
    faccHermanasdesc:"Yours truly other faction and the one that literally saved my life. They're a couple of small convents, each one lead by a different saint, from Katarina to Ophelia. Anyway, this congregation is focused in helping others, healing, medicine and raising the population and pleasure levels of the universe by a huge margin. They are now 'ruled' Great Saint Megumi of Life and ruled by her mother, Saint Alice of The Void. If you wanna have good sex, help people and be helped, come here!",
    faccFervortitle:"Zealite Arcanists",
    faccFervordesc:"The greatest experts in spiritism and intrasential science in the planet! Fuck that, IN THE WHOLE GALAXY! Long ago they were two different countries, but they ended up uniting in a sigle faction after Sanabaur's Ascension. Long story short, a lot of Intra, a lot of water and fire and a loooot of wine, all under the careful eye of the Fateweaver herself (As long as she's not drunk, of course)!",
    faccAprendizastitle:"Azxqerfo's Pupils",
    faccAprendizasdesc:"You like martial arts, illness and rust? Do you wanna learn about the benefits of shoving a nail up your ass? Would you like to test your worthiness with THE MAGIC STONE OF CONTROL? Call Doctor Azxqerfo for an appointment and let him train you with such prestigious fighters as Bea, Bea and.... BEA! A lot of the medical staff in the southern hemisphere comes out of here, but beware, their definition of healing is... a bit unorthodox",
    faccOasistitle:"Survivors of The Oasis",
    faccOasisdesc:"Ufff, this one's hard for what I can see. All the people in this faction are ex slaves who broke out of Hall's factories, and now they have been able to found their own planet in Western BiuTau. A faction based on cooperation, freedom and the love for an individualistic and fair life. And everything seems to be going well, as well as they can in a newly formed country. But Tiff does the best she can to keep everything together (By the Mother's Sweet Rubbery Tits, we're so proud of her).",
    faccHallYCotitle:"Hall &Co: Foods And Experiences",
    faccHallYCodesc:"Are you still around? I thought that after what happened to your bo... Ehem. Hall&Co, Hall&Co... The company who monopolized the production of anything that can be extracted from a malleable being... Mainly through slaving people who they milked like they were nothing more than bhurs or fruits. If you like money, slavery and exploitation (Oh, and reducing and torturing people so fucking much they don't even consider themselves people anymore), this is your faction, I guess...",
    faccEnclavestitle:"Free Enclaves",
    faccEnclavesdesc:"The most heterogeneous and varied faction of them all. Divided in captainships that work like the pieces of a perfectly oiled machine under the ruling and support of the Don of the Enclaves. You wanna cook? Go to the restoration district! You wanna make chemical stuff? PhlecksChem with recieve you with open arms! You wana drink? The Bubble's always open and Gums will always be there for you! But remember to pay your taxes and listen to the calls for help of your neighbors, or maybe no one will listen to yours.",
    faccTimarAurhumtitle:"The Golden Army of Timar Aurhum",
    faccTimarAurhumdesc:"Honorable, strong, mighty and professional! That's how the people of Timar Aurhum describe themselves (They usually forget to say they have a stick up their asses, but that may be a honest mistake). This proud country of soldiers, blacksmiths and miners is now being divided by a succession conflict. They have to choose wether to support King Aureliano, founder of the country and absolute expansionist ruler of it, or his daughter, Princess Electra, who wants to have a more diplomatic and respectful approach to international relationships. Which one would you choose?"
}
