const data_general_ENG= {
    "btESP":"Spanish",
    "btENG":"English",
    "tituloBtIdioma":"Choose your language",
    "tituloCargar":"Load and download",
    "descargar":"Download",
    "importar":"Import file",
    "importarDesc":"Choose a file to import",
    "nombreTitulo":"General information",
    "coloresTitulo":"Colors",
    "colorPelo":"Hair color",
    "colorPiel":"Skin tone",
    "colorOjos":"Eye color",
    "puntosTitulo":"Points",
    "creatorTitle":"Character Creator",
    "nombreImplementacion":"Implementation name",
    "logros":"Achievements",
    "labelNombre":"Name",
    "edadTitulo":"Select your birthday and age",
    "dias":"Day",
    "mes":"Month",
    "edad":"Age",
    pronombres:"Pronouns"
}

