const datos_intra_ENG={
    "Grupos-de-nucleos":"Core groups",
    "Nucleos-Elementales":"Elemental cores",
    "Nucleos-Sagrados":"Holy cores",
    "Nucleos-Profanos":"Unholy cores",
    "Nucleos-Naturales":"Natural cores",
    "Nucleos-Arcanos":"Arcane cores",
    Elementalestitle:"Elemental",
    Elementalesdesc:"Air, Earth, Water, Fire and Electricity. Thanks to the cores of the Wizard you'll be able to control the elements that constitute our world (As told by the arcanists and people which don't know about chemistry, of course)." ,
    Sagradostitle:"Holy",
    Sagradosdesc:"The absolute epythome of faith, purity and fanatism. With this cores touched by the Wizard and the Mother you'll be able to do anything luminous, healing and sterotypically pretty. But be careful not to become too faithful...",
    Profanostitle:"Unholy",
    Profanosdesc:"Uuuuuuuh, you wanna be a bad girl, huh? Fuckin' great! Raise the dead from their graves, read people's souls, rot everything around you and manipulate everyone with your dark gifts! (This space's been sponsored by the Association of Supporters of the Daemon Core)",
    Naturalestitle:"Natural",
    Naturalesdesc:"You know, the closest cores to The Boss (Or The Mother, however you wanna call her). With things like animals, plants, healing more stuff... Perfect if you like things that move, drool and grow!",
    Arcanostitle:"Arcane",
    Arcanosdesc:"The most mysterious and strange of them all. We don't really know why, but with this ones you'll be able to weave the threads of the fabric of reality. Space and time will surrender to your will. You'll see everything as a strange code. However, be careful not to become to close to the Strange...",
    Aguatitle:"Agua",
    Aguadesc:"¡Agua, fiesta, borrachera y felicidad! Probablemente de los núcleos a los que más les va la juerga, no llaman al anterior portador El Borracho por nada, ajaja. Eso sí, si vas a seguir a Sanabaur, más te vale llevarte un paraguas (Y una botella de vino)...",
    Airetitle:"Aire",
    Airedesc:"El núcleo de la velocidad y la conquista (Créeme, esta gente es muy pesada con 'El arte de la conquista' de Von Wenfen). Técnicamente debería ser imparcial, pero El Don de los Enclaves me paga, así que... ¡Este núcleo te hará volar por ahí y podrás inflarte como si fueras un globo (Que sé que a mucha gente le va eso)! Desde luego, es un soplo de aire fresco, jeje.",
    Fuegotitle:"Fuego",
    Fuegodesc:"Oh no, tenemos a un intensito por aquí. Por favor, no dejes que tu ardiente pasión y fervor te quemen los ojos (Literalmente, ¿No sabes lo que le pasó a Al-Azsj?). Menos mal que Sanabaur y las fervorianas están ahí para templarte y controlarte. Eso sí, ¿Y lo de putísima madre quemarlo todo a tu paso?",
    Tierratitle:"Tierra",
    Tierradesc:"Rígida como una piedra, maleable como el barro (Y fértil como la tierra abonada, claro, que sabemos quién lleva esto). ¡El núcleo de Santa Megumi! ¡Crea terremotos con tus pies, lanza rocas por los aires y sé más terca que una puta mula (Por algo llamaban así a Atxomedarian, La Mula Sísmica)!",
    Electricidadtitle:"Electricidad",
    Electricidaddesc:"Impredecible, caótica, estruendosa y guapísima, no se me ocurre mejor forma de describir tanto a Berbatho como a MADAMME CHISPAAAS (Estoy contractualmente obligada a llamarla así). Ya sabes cómo va esto, ¡El poder ilimitado del rayo y el trueno en la palma de tu mano! Por favor, intenta no freirle los cerebros a nadie, ¿Sabes el coñazo que es regenerarlos?",
    Luztitle:"Luz",
    Luzdesc:"Núcleo de las mentiras y el arte. ¡Si eres artista, podrás hacer que tus obras resalten todo y más! Tan solo, cuidado no te dejes absorber, mira cómo ha estado la pobre Thienna. Al menos no estafa a gente como el viejo Fixel...",
    Creaciontitle:"Creación",
    Creaciondesc:"Desde tiempos de Hana-Mesa-Hila, este Núcleo ha pasado de malas manos a malas manos. ¡Y normal, viendo que es el Núcleo de la censura (y templanza)! Menos mal que Hall desapareció bajo circunstancias misteriosas.",
    Canalizaciontitle:"Canalización",
    Canalizaciondesc:"¿Qué vamos a decir del Núcleo del fanatismo y la manipulación? Vale que podrás hacer cosas espirituales y canalizar el poder de otras personas, ¿pero no podría haber ido el control mental a otros Núcleos? Mientras no te presentes como un enviado divino como Mirfael o Sacra...",
    Restauraciontitle:"Restauración",
    Restauraciondesc:"Es cierto que todo suele tender al equilibrio, y este Núcleo es la representación de esto. Vaera la Constante y Carmen ambas son defensoras de sus respectivos status quo, ¿y normal, viendo que pueden restaurar, purificar o negar cualquier cosa!",
    Protecciontitle:"Protección",
    Protecciondesc:"Un Núcleo muy tocado por la Esencia de, bueno, la Protección. Normal que suela elegir a protectores y monarcas, como Axtor Custis o el Gran Rey Aureliano. ¡Eso sí, menudas espadas puedes crear en un momento con la metalomancia, y corregir sus fallos con anulación!",
    Faunatitle:"Fauna",
    Faunadesc:"Así que te gustan los animales, ¿Eh? Animales peludos, escamosos, babeantes, voladores... Pero más que nada, poderosos y vigorosos. ¡Abraza tu lado primitivo y salvaje y haz que te sigan! (No nos hacemos responsables de que te crezca pelo, escamas y cuernos y mucho menos de que vayas por ahí meándote por las esquinas. No seas como Ampithos, sé como Zoo'Mani)",
    Floratitle:"Flora",
    Floradesc:"El núcleo de las plantas, el crecimiento, la longevidad y lo verde en general. Si morir de vieja es difícil de por sí, ¡Con esto podrás vivir miles de años! (Aunque si te descuidas acabarás echando raíces y nutriendo a todo el mundo como Treiv y sus Daer'Triae) ¡Espero que te gusten las hojas! Ah, y saluda al Gran Maestro de nuestra parte, ¿Quieres?",
    Familiarestitle:"Familiares",
    Familiaresdesc:"Oye, tú. ¿Estás sólo? ¿Quieres algo que te haga compañía? ¿QUIERES FOLLARTE A TU PRI- (Mis abogadas no me permiten terminar este chiste por ser considerado de mal gusto en muchos países) ¡Pues este es tu núcleo! ¡Sigue las enseñanzas de Santos Zoo'Mani y genérate un amigo! (No nos preguntes por las implicaciones legales, morales o espirituales de jugar así con la vida, no quieres acabar en el exilio como los Diez Clanes).",
    Comuniontitle:"Comunión",
    Comuniondesc:"Una de dos, o te gusta ser el centro de atención de todas las situaciones en las que estás (Es decir, sigues a Adamarein) o eres una persona empática que comprende y quiere ayudar a todo el mundo (Es decir, no sigues ni a Adamarein ni a La Madre), no hay término medio. Seas lo que seas, si lo que quieres es conectarte con el mundo, sus habitantes y sus daemonios, ¡Estás en el sitio correcto!",
    Adaptaciontitle:"Adaptacion",
    Adaptaciondesc:"No puedo describirte, bueno, ni a ti ni a este núcleo. ¿Por qué? Porque NUNCA DEJA DE CAMBIAR. No por nada es el núcleo más cercano a la Esencia de La Vida (Por algo lo llevaba La Madre, ¿No?). Contempla el entorno, recibe estímulos y cambia, transfórmate y EVOLUCIONA para adaptarte a todo. (Lo que no termino de entender es por qué las portadoras siempre han estado en el Espectro, pero eh, las preguntas a La Jefa y a La Subjefa Cam).",
    Oscuridadtitle:"Oscuridad",
    Oscuridaddesc:"Así que quieres ser el señor de la noche, los secretos y la confianza, ¿Eh? Bueno, siempre puedes pedirle consejo al Don, afortunadamente. Controla las sombras, acapara los secretos más oscuros de la gente y aprovéchate de la confianza que tienes con ella siguiendo las enseñanzas del Confidente. ¡El núcleo perfecto para los informantes (O los taberneros)!",
    Daemoniostitle:"Daemonios",
    Daemoniosdesc:"¡Daemonios, conspiraciones y pactos! Ahh, el núcleo de las contradicciones y el poder político en general (A Cael'Ar'Mun se le llama Lord e instigador de rebeliones por algo). Arrímate a los gobernantes y cuando estén demasiado cómodos... ¡Apoya a los gobernados para desestabilizarlo todo! Con esto tendrás el destino de la sociedad y la política en la palma de tu mano (Ah, y también puedes invocar daemonios y espíritus, aunque el Don no lo haga. Mola, ¿No?).",
    Putrefacciontitle:"Putrefaccion",
    Putrefacciondesc:"Eww... ¿De verdad te gusta esto? A ver, sí, controlar las enfermedades es útil y los seguidores del Maestro Az son gente muy centrada y solidaria (A ver, lleva siendo así desde los tiempos de Praktheed, así que no me sorprende). Pero espero que comprendas que no me guste estar con gente que no solo se está pudriendo en vida, sino que también pudren y corroen todo su entorno... Y huelen fatal.",
    Muertetitle:"Muerte",
    Muertedesc:"Mmmmm, el dulce consuelo de la muerte, tan dulce como las obras de Armonía, la Pastelera de Libertas. La garantía de que La Justa pondrá a todo el mundo en su lugar. A mí me parece un poco aburrido, pero si lo que quieres es ver y manipular almas y alzar a los muertos para que hagan las cosas por ti, siempre puedes seguir la senda de la nigromancia. (O eso o te dedicas a las leyes y la justicia, lo cual hace que sea más aburrido todavía) ",
    Vaciotitle:"Vacío",
    Vaciodesc:"Sexo, el chiste es sexo. Nah, pese a lo que pueda parecer, este núcleo tiene mucho más que simplemente la Succión y los tentáculos. El núcleo de la belleza, la locura, la gravedad y la Nada, perfecto para la gente que quiera ser bailarina en un pub de mala muerte como Phradi. O también puedes ayudarnos un poco en la Congregación bajo la atenta mirada de Santa Alicia, lo que quieras... (Sí, también estoy contractualmente obligada a hacernos propaganda, así que ¿EH,TÚ? ¿TE GUSTA FOLLAR Y LOS TENTÁCULOS? PUES VEN AQUÍ)",
    Espaciotitle:"Espacio",
    Espaciodesc:"Ufff, este ha tenido controversias hace poco. El Núcleo del Espacio, la Continuidad y la Gestión en su momento fue portado por Daeda Run, la Tejedora, y recientemente por una abogada, Straw, de la que no vamos a hablar... Sus Llamadas de transporte, control espacial, y relatividad pueden ser muy útiles, pero asegúrate de darles un uso un poco mejor que la que le dio la última",
    Tiempotitle:"Tiempo",
    Tiempodesc:"Seguramente el Núcleo más peligroso, por su potencial y de quién viene la mayor parte de su poder, el Extraño. Gracias a la Madre (gracias también por el aumento, jefa), ha sido siempre portado por personas con al menos dos dedos de frente, como Zaio, el Archivador, y Santa Katarina, jefa actual de las Hermanas. Además, quien porte este Núcleo tiene la titánica tarea de mantener la consistencia del universo y la línea temporal. ¡Gracias, Kate!",
    Ritostitle:"Ritos",
    Ritosdesc:"¡Este es el mío! Ideal para gente, como yo, que sepa de programación. Ritos, Metodismo, y Estudio son los tres aspectos de este Núcleo, y con él, puedes programar en la misma realidad, permitiéndote hacer cualquier cosa desde una moneda que vibre si intentan entrar a tu casa hasta programar un edificio entero para que se adapte a las necesidades y deseos de quien haya dentro (aviso, no viene con conocimientos de interiorismo). Eso sí, apunta todo lo que hagas y funciona, no te estés pegando con un fallo durante semanas porque se te ha olvidado definir una variable",
    Evocacióntitle:"Evocación",
    Evocacióndesc:"Evocación, Máquinas y Leyes... Es una pena que uno tan útil esté en manos de Smith, y más después del uso ejemplar que le dio Maerul, que impulsó la tecnología enormemente en su momento. Puedes mirar una máquina y entender hasta su más mínima parte perfectamente, y recrearla casi con dos palos y un escupitajo, o puedes usar su parte más aburrida para manipular textos e imponer en parte tu voluntad a tu alrededos. De verdad, teniendo potencialmente ordenadores infinitos, ¿quién querría andar cambiando un par de palabras por ahí?",
    Interaccióntitle:"Interacción",
    Interaccióndesc:"Este es de mis favoritos, no sabes lo bien que me vendría tener uno o dos daemonios de este... Aunque, eso es algo que diría casi cualquier persona. Interacción se basa en, bueno, las interacciones, desde el punto de vista físico, químico, intraesencial... ¡Te permite combinar las cosas mucho más fácilmente! Y eso, combinado con su inventiva, el ser capaz de ver probabilidades, y ser capaz de dividir todo a sus componentes más básicos para después recombinarlos, lo hace seguramente el Núcleo más versátil junto con Adaptación"
}
