const datos_intra_ENG={
    "Grupos-de-nucleos":"Core groups",
    "Nucleos-Elementales":"Elemental cores",
    "Nucleos-Sagrados":"Holy cores",
    "Nucleos-Profanos":"Unholy cores",
    "Nucleos-Naturales":"Natural cores",
    "Nucleos-Arcanos":"Arcane cores",
    Elementalestitle:"Elemental",
    Elementalesdesc:"Air, Earth, Water, Fire and Electricity. Thanks to the cores of the Wizard you'll be able to control the elements that constitute our world (As told by the arcanists and people which don't know about chemistry, of course)." ,
    Sagradostitle:"Holy",
    Sagradosdesc:"The absolute epythome of faith, purity and fanatism. With this cores touched by the Wizard and the Mother you'll be able to do anything luminous, healing and sterotypically pretty. But be careful not to become too faithful...",
    Profanostitle:"Unholy",
    Profanosdesc:"Uuuuuuuh, you wanna be a bad girl, huh? Fuckin' great! Raise the dead from their graves, read people's souls, rot everything around you and manipulate everyone with your dark gifts! (This space's been sponsored by the Association of Supporters of the Daemon Core)",
    Naturalestitle:"Natural",
    Naturalesdesc:"You know, the closest cores to The Boss (Or The Mother, however you wanna call her). With things like animals, plants, healing more stuff... Perfect if you like things that move, drool and grow!",
    Arcanostitle:"Arcane",
    Arcanosdesc:"The most mysterious and strange of them all. We don't really know why, but with this ones you'll be able to weave the threads of the fabric of reality. Space and time will surrender to your will. You'll see everything as a strange code. However, be careful not to become to close to the Strange...",
    
    Aguatitle:"Water",
    Aguadesc:"Water, party, booze and joy! One of the most outgoing and party loving cores out there, probably, they don't call its former wielder The Drunk for nothing, ahahhah. However, if you're really going to follow Sanabaur, you'd better always have an umbrella (Or a bottle of wine) nearby...",
    Airetitle:"Air",
    Airedesc:"The core of speed and conquest (Trust me, this guys are really annoying with Von Wenfen's 'The art of conquest'. I should technically be neutral, but the Don of the Enclaves pays me, so... This core will make you fly all over the place and you can even inflate like a balloon (I know some people 'enjoy' that)! It is, indeed, a breath of fresh air, hehe",
    Fuegotitle:"Fire",
    Fuegodesc:"Oh no, we have an edgy one around here. Please, don't let your fiery passion and zeal burn your eyes to a crisp (Literally, you don't want to end like Al-Azjs, do you?). Well, fortunately Sanabaur and the zealites are always there to cool you down and keep everything under control. But, wouldn't it be cool as fuck to be able to burn everything around you?.",
    Tierratitle:"Earth",
    Tierradesc:"Stiff as a rock, malleable like clay (And fertile as wet dirt, of course, we all know who bears this one). The core of Saint Megumi! Create earthquakes with your feet, throw rocks to the sky and be as stubborn as a fucking mule (Where did you think Atxomedarian's, The Seismic Mule, nickname came from?)",
    Electricidadtitle:"Electricity",
    Electricidaddesc:"Unpredictable, chaotic, loud and awesome, I don't know a better way to describe both Berbatho and MADAMMEEEE SPAAAARKS (I'm bound by a contract to call her like that) You know how this goes, The unlimited power of lightning and thunder in the palm of your hand! Please, try not to fry anyone's brains, they are a pain in the butt to regenerate.",
    Luztitle:"Light",
    Luzdesc:"The core of lies and art. If you're an artist you'll be able to make your pieces stand out and more! But careful not to let it consume you, look how poor Thienna's been the last few months. Well, at least she's not a scammer like old Fixel.",
    Penitenciatitle:"Penance",
    Penitenciadesc: "This core has been passed from bad hands to even worse ones since the time of Hana-Mesa-Hila. Quite understandably, since it's the core of censorship (And temperance)! At least Hall has been missing in action for a while now.",
    Canalizaciontitle:"Channeling",
    Canalizaciondesc: "What can we say about the core of fanatism and manipulation? Yes, you'll be able to do spiritual stuff like channeling other people's powers, but couldn't mind control have ended up in any other core? As long as you don't sell yourself as some kind of divine harbinger like Mirfael or Sacra...",
    Restauraciontitle:"Restauration",
    Restauraciondesc:"It's a fact that everything tends to balance, and this core is the embodiment of that. Vaera the Constant and Carmen are both stoic defenders of their respective status quo, and who wouldn't, seeing that they can restore, purify and deny anything!",
    Protecciontitle:"Protection",
    Protecciondesc:"A core deeply in touch with the Essence of, well, Protection. It tends to choose protectors and monarchs, just like Axtor Custis or Great King Aurelian. But screw that, you can make cool as fuck swords with metallomancy, and correct their mistakes with nullifying!",
    Faunatitle:"Fauna",
    Faunadesc:"So you like animals, huh? Furry, scaly, slimy, flying... But most importantly, powerful and vigorous animals. Embrace your primal and wild side and make them follow you! (We're not responsible for any growth of hair, scales or horns and even less responsible for you urinating in every corner. Don't be like Ampithos, be like Zoo'Mani)",
    Floratitle:"Flora",
    Floradesc:"The core of plants, growth, longevity and everything green. If dying of natural causes is hard per se, with this you can keep on living for milennia! (But if you're not careful you'll sprout roots and begin nurturing everyone like Treiv and her Daer'Triae) Hope you like leaves!",
    Familiarestitle:"Familiars",
    Familiaresdesc:"Hey, you. Do you feel lonely? Do you want something to be with you forever and ever? DO YOU WANT TO FUCK YOUR COUS- (My lawyers have advised me not to finish this joke due to it being considered as offensive in a lot of countries) This is your core! Follow the teachings of Saints Zoo'Mani and make yourself a friend! (Don't question us about the legal, moral or spiritual implications of playing with life like that, you don't want to be exiled like the Ten Clans)",
    Voluntadtitle:"Will",
    Voluntaddesc: "Well, well, well... A main character! Nah, now seriously, if you choose this core is that you clearly have (Or want to have) a willpower so strong that it makes the whole world (Literally, not only the people in it) bow to your will, and you know what? Go on! Follow your dreams! Squash and stretch the world and its logic! Make physics be your little bitch! BE FREE! (Riuter Laboratories is not responsible to the crazy stuff that can be done with this core, blame Saint Megumi, as she's the wielder)",
    Adaptaciontitle:"Adaptation",
    Adaptaciondesc:"I can't describe you, well, neither you nor this core. Why, you ask? Because it's ALWAYS CHANGING. It isn't called the closest core to the Essence of Life for nothing (The Mother was its bearer, so...). Examine your surroundings, react to stimuli and change, transform and EVOLVE to adapt to everything. (But what puzzles me is why its vessels are always in the Spectrum, but hey, ask The Boss and the Miniboss Cam) ",
    Oscuridadtitle:"Darkness",
    Oscuridaddesc:"So you want to be the master of night, secrets and confidence, huh? Well, you can always ask the Don for some advice, fortunately. Control shadows, be the keeper of the darkest secrets and take advantage of people trusting you following the teachings of the Confident. The perfect core for informants (Or bartenders)!",
    Daemoniostitle:"Daemons",
    Daemoniosdesc:"Daemons, conspiracies and pacts! Ahhh, the core of contradictions and political power in general (Cael'Ar'Mun is called the igniter of rebelions for someting). Get close to the people in power and when they are a bit too comfortable... Support the subjects to destabilize everything! With this you'll have the fate of society and politics in the palm of your hand (Oh, and you can also summon daemons and spirits, even though the Don doesn't usually do it. Cool, isn't it?)",
    Putrefacciontitle:"Rot",
    Putrefacciondesc:"Ewww... Do you really like this? I mean, controlling infections is useful and the followers of Master Az are really generous and focused people (It's been like that since the times of Praktheed, so it's not surprising at all) But I hope you understand me not liking to be with people who are not only rotting alive themselves, but also everything around them... And they reek.",
    Muertetitle:"Death",
    Muertedesc:"Mmmmm, the sweet release of death, as sweet as Armonia 'The baker of Libertas' and her cakes. It's guaranteed that the Fair will put everyone in their place. I think it's a bit boring, but if what you want to do is to manage souls and raise the dead from their graves to make them do things for you, you can always follow the way of the necromancer. (You can also focus in laws and justice, which makes it even more boring) ",
    Vaciotitle:"Void",
    Vaciodesc:"Sex, the joke is sex. Nah, despite what many people believe, this core has a lot more than Suction and tentacles. The core of beauty, madness, gravity and the Nothingness, perfect for people who want to be a dancer in a pub like Phradi. Or you can also help us a bit in the Congregation under the caring eye of Saint Alicia, whatever you want... (Yes, I'm also bound by a contract to sell it to you, so... HEY, YOU, DO YOU LIKE FUCKING AND TENTACLES? COME HERE, THEN",
    Espaciotitle:"Space",
    Espaciodesc:"Ufff, this has had its own load of controversies quite recently. The core of Space, Continuity and Management was once wielded by Daeda Run, the Weaver, and recently by a lawyer, Straw, let's not talk about her, please... Its calls of transport, spatial control and relativity can be really useful, but make sure to use them in a better way than her",
    Tiempotitle:"Time",
    Tiempodesc:"By far the most dangerous core, both by its potential and the source of most of its power, The Strange. We should thank the mother (Thank you also for the raise, boss) as it has always been wielded by sensible people, like Zaio, the Archivist, and Saint Katarina, current ruler of the Sisters. Also, whoever wields this core has to endure the titanical task of keeping the consistency of the timeline. Thank you, Kate!",
    Ritostitle:"Rites",
    Ritosdesc:"Oh, this one's mine! Ideal for people, like myself or the great crafters of Rutgo, who knows about coding. Rites, Methodism and Study are the three aspects of this core, and with it you can reprogram reality itself, letting you make anything, from a coin that vibrates whenever someone tries to break in your house to even program an entire building to fulfill the needs and wishes of whoever is in it (Warning, interior design skills not included). But you should write down everything you do that works, you don't want to be fighting an issue for weeks just because you forgot to declare a variable."
    ,
    Evocacióntitle:"Evocation",
    Evocacióndesc: "Evocation, Machines and Laws... What a shame such a useful core is in Smith's hands, and even worse after the perfect use Maerul gave it, who advanced the technology in a huge way. You can look at a machine and understand it to its smallest components, and even rebuild it using two sticks and a spit, or you can just focus on the boring stuff, altering texts and doing your will around you. Seriously, having virtually inifinite computers, who would want to go around there changing a few words?",
    Interaccióntitle:"Interaction",
    Interaccióndesc:"One of my favorites, you don't know how having a couple of its daemons would come in handy... But anyone would tell you that. Interaction focus on, well, interactions and synergies, physical, chemical, intrasential... It makes mixing and combining things way easier! So, yeah, if you combine that with enough inventive and creativity, the ability to see probabilities and being able to divide everything to its smallest components just to recombine them later, makes this core the more versatile one, besides Adaptation, of course"
}
